const kFiles = [
	{
		type: "text",
		name: "Dearest_Anna_Please_Read_Important.txt",
		unlocks: "sample1.jek",
		key: "",
		text: "My Dearest Anna,\n\nIf you are reading this, then I am already dead.\n\nGood lord, what a cliche. You probably hate that I wrote that. You're probably rolling your eyes. Are they damp, I wonder? After all that's happened, do you have tears left for me?\n\nBut enough of that, I was talking about cliches. I hope you'll forgive that one. I have quite a bit to tell you, things that I'm sorry to say will be confusing and horrible. So perhaps lingering on a worn out old trope for a moment longer isn't such a bad way to start.\n\nAnd so I'll repeat it - I am dead. And with me I've taken all of my research. I told you many times over the years, when you were still inclined towards asking, that my work was important. That it might well be the most important work any human mind has ever been burdened with. That was true. I've told you so many lies over the years - and I beg you to forgive me Anna - but that much was true.\n\nBut now my work is gone. Burned, destroyed, every last hint at my studies has been purged, except for this. I pray that you've found it and only you, that you're reading this, and that not too great a span of time has passed since my death.\n\nWhat I say next, I hope you'll take with the utmost sincerity. Not for the sake of my memory, or the love we once shared (that I still to this day hold for you, whether or not you can believe that), but for the sake of our daughter's life, which I tell you now hangs in the balance. You must read all I've left here for you. Read it carefully, commit it to heart, and follow my instructions.\n\nThis partition contains a series of files that I've left for you. You must inspect each of them, carefully and in order. Some are text, the rest are a selection of recordings of experimental data. After viewing each you will be given a key that will allow you to open the next.\n\nI'll leave you now to view the next file, though it pains me. I've left you ten thousand times before with less fuss, but I promise you with heartbreak each time. But the truth is we've parted for the final time already.\n\nsample1.jek\n\nbeginning",
		earnedKey: "beginning",
	},
	{
		type: "game",
		name: "sample1.jek", 
		unlocks:"pandora.txt", 
		key:"beginning",
		earnedKey:"bliss",
	},
	{
		type: "text",
		name: "pandora.txt",
		unlocks: "sample2.jek",
		key: "bliss",
		text: "Hello Anna,\n\nI'm glad you're still reading. I knew you would. You always had such a curious mind. I've always loved that about you, even though it was a torment to me in the end. If you had been average, I wouldn't have had to tell you so many lies.\n\nBut, oh yes, you're wondering what it was you just saw. That was a colony of the local fungus Paraisaria pandora, of the family Ophiocordycipitaceae. I found the strain that first year in the summer house while examining a slide full of pond water from the yard. At first I was only making sure the movers hadn't damaged any of my equipment, but then I thought I'd get to know the local flora - so I recorded a time lapse as it metabolized a crumb of an egg salad sandwich.\n\nRemember how that summer we ate egg salad sandwiches? Every day for lunch, it was an egg salad sandwich. You were pregnant with Lisa and what a strange craving. Then you gave birth and after that you said they were revolting. I don't think I've eaten an egg salad sandwich since, but the smell of them always brings me back to that summer...\n\nDo you like the name? I came up with it myself. As far as I know Paraisaria pandora hasn't been recorded by any other human. That may be because it's rare - for all I know it exists solely in our little backyard pond - but more likely it's simply because it's unremarkable. There are millions of uncatalogued samples of aquatic specimen around the world, waiting in cupboards for science to slowly sort them out.\n\nAnd Paraisaria pandora is unremarkable. It should be unremarkable. It's a decomposer, like all fungi. It moves by growth, an opportunistic eater that searches its environment for food, feeding primarily on algae or plant matter suspended in the water. It isn't a threat to anything with a healthy immune system, no more than any of the other millions of microorganisms swimming in a glass of pond water.\n\nThe only curious trait I observed was the pattern of its growth. As it searched the slide for resources it methodically reached out in one direction and then the next, almost intelligently, until it found something organic to metabolize. And once it did, its growth exploded. The colony expanded as it consumed until there was nothing left of the original material and in its place the colony had formed an almost perfect copy.\n\nParaisaria pandora isn't unique in this trait, although the fidelity of the copy was unusually impressive. The resulting growth matched the structure of the organic material it consumed down the the cellular level. This is ultimately what inspired me to attempt my second experiment with the fungus. I collected a handful of tadpoles from the yard, stunned them in an ethanol bath, and then moved them into a solution containing Paraisaria pandora.\n\nsample2.jek\n\nopen",
		earnedKey: "open",
	},
	{
		type: "game",
		name: "sample2.jek",
		unlocks: "dead_tadpoles.txt",
		key: "open",
		earnedKey: "frozen",
	},
	{
		type: "text",
		name: "dead_tadpoles.txt",
		unlocks: "sample3.jek",
		key: "frozen",
		text: "I left the tadpoles and solution in a jar on my desk in the basement and then promptly forgot about them. The house was still a mess and we were in a frenzy getting everything ready for the baby.\n\nYou had labeled everything so carefully, but the movers had mixed up all our boxes, so whichever one we opened was sure not to have what we were looking for and to launch a roving hunt all through the house. One night you caught me in the hall with an aquarium full of books under one arm and a DVD player under the other and asked me what I was doing. I told you I was making a cup of coffee, of course, and you laughed so hard I had to drop it all to help you down to the floor.\n\nDuring the days, I was settling in at the university and you were painting Lisa's room blue. That was when we still thought she was going to be a boy. From her very first day she was defying expectations.\n\nA week had passed before I thought about my little experiment again and found a spare moment to go check on it. In the dim light of the basement, the jar of water had taken on a mossy green hue. I set it under a light and peered in. I could see the wriggling shadows of a handful of healthy tadpoles. They had apparently survived their ethanol bath and been too resilient to succumb to fungal infection. There were also a few motionless shadows, floating at about mid depth in the jar.\n\nI took a spoon and fished one of the motionless tadpoles out onto a paper plate and held it under the light. It was a dull green and covered with a wisp of fuzz. I prodded it and it broke apart, revealing a fibrous interior of uniform texture. It was at that moment I realized it wasn't a tadpole at all, but the remains of a fungal colony that had consumed one and taken on its exact shape. The tadpole had likely died quickly after being moved into the jar, providing a defenseless meal for the fungus. The detail was amazing, the colony perfectly mimicked the shape of a tadpole, down to the contours of it eyes and nostrils, and the tiny filaments lining its mouth.\n\nsample3.jek\n\nstronger",
		earnedKey: "stronger",
	},
	{
		type: "game",
		name: "sample3.jek",
		unlocks: "conclusions.txt",
		key: "stronger",
		earnedKey: "taxidermy",
	},
	{
		type: "text",
		name: "conclusions.txt",
		unlocks: "sample4.jek",
		text: "I must pause my story here. At this point, a conclusion may be forming in your mind - one that may find support among the notions and prejudices against me you may have formed over the years. This is a very dangerous thing because I assure you whatever assumptions you are drawing at this point cannot possibly approach the truth. As I wrote previously, your full understanding and belief of our situation is a matter of life and death.\n\nSo I'll declare now, hopefully before the thought has caught indelible in your mind, that these small morbid experiments with tadpoles in our basement do not amount to the life's work that has stolen us from each other. I did not cloister myself away, neglecting you and Lisa as I did for decades - and yes, I'll admit that's what I've done - in order to develop some macabre form of living taxidermy. I am not mad. More important than anything else, I need you to believe that.\n\nAs you continue to read I'll provide you what proof I can that what I say is true. I've saved some scraps that I hope will lend more weight than words alone can. But for now the proof I offer is in asking you to think back to that summer. To the time we spent together. To the moments we shared as we welcomed our baby daughter into the world.\n\nThese memories are the clearest I have, and the ones I've cherished the most. I've spent countless hours examining them - turning them over like tattered photographs in my mind, alone in our basement, you and Lisa just upstairs but impossibly distant. I've lived a life accumulating few more and none as joyful. I hope you've bothered to hold onto these memories, that you can still remember us the way we were then.\n\nI can spark your memory if I must. We were deeply in love. We were the center of each other's universes. And then Lisa arrived, and we orbited her together. I read aloud to you both while she gurgled in your arms. You painted me asleep with her on my chest, both of us drooling. We changed diapers and warmed bottles and repainted the nursery pink but then just kept the crib in our bedroom anyway. We fretted over her first cold, and every time she cried, and one night I raced her to the doctor's office when her nose bled only to be sent home with a scolding and a box of tissues.\n\nI was not a man obsessed with his work. I was there with you. We should have had more time like that. We deserved it.\n\nsample4.jek\n\nspark",
		key: "taxidermy",
		earnedKey: "spark",
	},
	{
		type: "game",
		name: "sample4.jek",
		unlocks: "synchronized.txt",
		key: "spark",
		earnedKey: "mass",
	},
	{
		type: "text",
		name: "synchronized.txt",
		unlocks: "sample5.jek",
		key: "mass",
		text: "I'll return now to the tadpoles, reluctantly, because they do still have their part to play. I've spent so much time rehearsing the telling of this story. Countless hours spent sitting here at my desk, desperate to spill it out to you, while you read or paint or do I truly do not know what just a couple flights of stairs away. But instead I trudge upstairs long after you've fallen asleep to lay wordlessly beside you. I'd rather linger longer telling the happier parts of this story, those are the parts I retell to myself on nights like these, when I can barely restrain myself from rushing upstairs and spilling it all out to you in person, a final cathartic confession in the days before my death.\n\nI want to tell you everything. Know that. But I can't. Not before everything is in place. And by then it will be too late.\n\nBut back to the tadpoles.\n\nDespite everything else, I did find time to repeat my tadpole experiment. Not because of any morbid fascination with the furry green bodies that resulted, but because of something strange I noticed one afternoon while penning a letter at my desk. I sat down to write, affording a quick glance to the blurry wriggling shapes in the jar under the light, and then set to work. When I looked up again, what could have been only 10 or 20 minutes later, I saw something peculiar. Every single living tadpole had risen motionless to the surface of the water.\n\nI grabbed the jar and inspected it more closely. The floating bodies were completely untouched by the fungus. Their skin was still shiny and dappled. One or two twitched. I scanned the murky water and confirmed that not a single living tadpole continued to wriggle around in its depths. In a span of only a few minutes, every one of them had died.\n\nI could have chalked it up to coincidence and assumed that the tadpoles had died because of the subpar environment a jar in a basement provides. However, I had been feeding them a sliver of lettuce now and then, when I thought of it - and after all, they had all survived this long. For them to all expire at once seemed extremely unlikely.\n\nI performed the experiment three more times. Each time about half of the tadpoles died immediately and were consumed by my growing sample of Paraisaria pandora, forming ghostly green simulacrum of tadpoles that floated in the cloudy water. The other half of the tadpoles survived unaffected, until 26 days and between 18 and 19 hours later, at which point every remaining tadpole died simultaneously.\n\nsample5.jek\n\ncurious",
		earnedKey: "curious",
	},
	{
		type: "game",
		name: "sample5.jek",
		unlocks: "inside.txt",
		key: "curious",
		earnedKey: "dissection",
	},
	{
		type: "text",
		name: "inside.txt",
		text: "The startling consistency of the phenomenon established, I couldn't resist investigating further. On the evening of the conclusion of the fourth experiment I put Lisa to bed, waited until you were asleep, and then crept down to the basement with a baby monitor so that I could examine the freshly deceased tadpoles in privacy before the Paraisaria pandora consumed them entirely.\n\nI fished out the small, slimy corpses and laid them out lengthwise on a section of cardboard. The members of the previous rounds I had packed and sealed in the large box freezer, and now I retrieved them as well, arranging them directly below my desk lamp to thaw.\n\nThe tadpoles were of the species Lithobates palustris, the offspring of the dark spotted pickerel frogs that kept you awake so many nights that first summer with their incessant calling. I'd borrowed a reference from the university and laid it open beside me before thumbing to the page I'd marked.\n\nI began by rinsing a tadpole with distilled water and inspecting its exterior. It appeared perfectly normal, with no visible sign of fungal infection. Next I made a shallow ventral incision and pinned it, spread open, to the cardboard. I wasn't sure what I expected to see. The diagram I had available was only sufficient to identify the species and its major organs, not to determine cause of death.\n\nBut I had already exhausted all other avenues to explanation. I ruled out deoxygenation and toxic buildup when tadpoles migrated to the jar after a mass die-off thrived. I ruled out the environment of the basement as the killer by keeping an uninfected jar of tadpoles alive for over 40 days. Tadpoles uncompromised by an ethanol bath also thrived in the infected water, failing to die off on schedule. And so, the only explanation was that the colony was able to affect some physiological change on the weakened tadpoles, one that only managed to kill them after an incubation time of almost a month.\n\nI observed the swirl of intestines, the pale tissue that formed the precursor to lungs, a tiny heart that twitched intermittently. I began to doubt that I'd be able to find any visible evidence of what killed the creature. But then, as I lengthened the incision to the anterior, the scalpel suddenly released a small discharge of rust colored goo, mottled with a crumbled greenish material.\n\nI smeared a small portion of the material on a slide. Under the microscope it was clear that the material was the remains of tissue destroyed by an infection of Paraisaria pandora. I rinsed the specimen and inspected the void where the liquified tissue had been. It seemed the colony had managed to gain a foothold in the soft tissue of the tadpole's gills, eating them away and killing it by asphyxiation.\n\nsample6.jek\n\nbreathless",
		unlocks: "sample6.jek",
		key: "dissection",
		earnedKey: "breathless",
	},
	{
		type: "game",
		name: "sample6.jek",
		unlocks: "parasite.txt",
		key: "breathless",
		earnedKey: "duplication",
	},
	{
		type: "text",
		name: "parasite.txt",
		text: "The cause of death for the tadpoles was established, infection of the soft tissues of the gills by Paraisaria pandora. One by one I dissected each freshly deceased tadpole, and then the thawed tadpoles from the freezer for good measure. Each displayed the same damage, gills destroyed by fungal infection.\n\nHowever, this told me nothing to explain the original mystery, the eerie synchronicity of their deaths. If anything, it raised further questions. The damage to the gills was complete, as though they'd liquified all at once, which ruled out a gradual deterioration of the tissues by a slow moving infection. But if the colony was ravaging the tissue instantaneously, what mechanism prevented the fungus from taking hold for weeks, and what made it fail all at once?\n\nI retrieved a live tadpole from a jar, an unlucky specimen from the fifth round of my experiment. It had been four days since it had been immunocompromised and then introduced to an environment containing Paraisaria pandora. I pinned it to the cardboard and made a practiced incision, then pulled back the tissue to reveal the tadpole's internal gills.\n\nThe tissue appeared healthy, with no signs of damage or infection. The soft filaments were packed tightly in hundreds of uniform fleshy ribs, all of them flexing and straining in tandem as the tadpole asphyxiated. The color was dark green, tinged crimson by the capillaries which were scaffolded by the intricate netting of flesh. Using the scalpel I pared a sliver of the tissue and placed it carefully on a slide.\n\nI was searching for the signs of preliminary infection, and I found them immediately. The viewscope filled with the familiar latticed structure of a cluster of Paraisaria pandora cells. I reduced magnification, expecting to see the cluster resolve into a fibrous speck nestled within the filaments of the tadpole's gills. Instead, it blurred out of view and then melted into the meaty threads. I increased magnification again, panned slightly past the pulsing red of a suffocating capillary, and again found a dense cluster of fungal cells. I panned about, confirming the cluster covered significant area, and reduced magnification, but again the view blurred then resolved to an unblemished view of healthy gill tissue.\n\nI repeated the exercise multiple times before I could accept what I was observing. When presented with the unbelievable a single point of proof isn't adequate, the mind requires proof in rounds, administered over time, for it to truly sink in.\n\nThere was no pocket of fungus nestled among the gill tissue, slowly eating and growing. There was no gill tissue at all. The surviving tadpoles did not fend off infection until their immune systems finally gave out weeks later. They had succumbed to infection immediately. Particles of Paraisaria pandora had lodged in the soft tissue of their gills and in their peculiar manner had exploded with growth, devouring cells and then growing into their place, quickly forming a colony that perfectly mimicked the structure of gills.\n\nIn a miraculous adaptive quirk, the fungus did not metabolize vascular tissue. Instead, it grew around it, exactly replicating the finely threaded latticework of the tadpole's gills, which supported and spread the tadpole's capillaries. In doing so, it actually replaced the tissue it consumed, the colony itself became functioning gills.\n\nThe sudden death of the tadpoles was not predicated on an overwhelmed immune system finally giving in to infection. In fact, the exact opposite was true: The tadpoles died moments after their traumatized immune system managed to reject their transplanted gills. The fungus adapted marvelously, but could only hide for so long before it was identified as foreign material, at which point blood flooded to the colony, antibodies broke down the fungal tissue, and in a matter of moments capillaries ruptured, tissue dissolved, and the entire structure crumbled into an unbreathing mass of crimson jelly.\n\nsample7.jek\n\njelly",
		unlocks: "sample7.jek",
		key: "duplication",
		earnedKey: "jelly",
	},
	{
		type: "game",
		name: "sample7.jek",
		unlocks: "finished.txt",
		key: "jelly",
		earnedKey: "euthanize",
	},
	{
		type: "text",
		text: "I euthanized the remaining tadpoles. The phenomenon was fascinating, but the mystery had been solved and I found myself developing an uncomfortable empathy for the doomed creatures. I felt a persistent scratching in my throat whenever I thought of them. So I dumped the contents of the jars back into the pond and sterilized my workstation. On a last-minute impulse I sealed a sample of Paraisaria pandora in a plastic bag and stored it away in the box freezer. I had an associate in mind who might be interested in it for a future paper.\n\nAnd then I forgot about all of it. Our lives were full, and I deemed the experiment too grisly for dinner conversation, so I never even mentioned it to you. Life went on, happily.\n\nsample8.jek\n\nover",
		name: "finished.txt",
		unlocks: "sample8.jek",
		key: "euthanize",
		earnedKey: "over",
	},
	{
		type: "game",
		name: "sample8.jek",
		unlocks: "life.txt",
		key: "over",
		earnedKey: "time",
	},
	{
		type: "text",
		name: "life.txt",
		text: "We were so full of hope that first year. Lisa was happy and healthy, growing, babbling, crawling all over the place. You were featured in some gallery - I can't recall where now, but I can remember one piece. You painted our home, but stretched tall and gleaming white as if made from stone. On all sides it was crowded by surging brambles and vines that clung and climbed up the walls. You titled it 'Castle'. I didn't tell you, but at the time I thought it might be a commentary on yard work.\n\nWe were so happy and it felt impossible that we wouldn't always be happy. And then everything went wrong so quickly. I lost my grant at the university. And we were beginning to worry about Lisa. It was a little over a year since she was born and the doctors all said she should be beginning to form words. And of course, that was the year my mom died. My brother called to let me know that after all these years she'd finally done it. At least the inheritance took the pressure off after I left work.\n\nIt was a lot to deal with at once. Too much. Lisa stopped babbling, her hands and legs stiffened. We saw doctors and they told us she was suffering from an unidentified neurological disorder, that with time and money we might see some improvement. You stopped painting. I had my first rough patch with drinking.\n\nLisa wasn't just delayed, she was getting worse. We could both see it, but no one could tell us why, or how to stop it.\n\nsample9.jek\n\ncastle",
		unlocks: "sample9.jek",
		key: "time",
		earnedKey: "castle",
	},
	{
		type: "game",
		name: "sample9.jek",
		unlocks: "dream.txt",
		key: "castle",
		earnedKey: "nightmare",
	},
	{
		type: "text",
		name: "dream.txt",
		text: "I had a dream about the tadpoles. I don't recall how it went, but I remember waking up drenched in sweat with the image of wriggling shadows in murky green water fading into recent memory. Lisa was crying and my mouth was dry, so I got up. Even her cry had changed, from a healthy bawl to a plaintive wail. I picked her up and braced her, squirming, against my shoulder, then padded toward the kitchen for a glass of water.\n\nI couldn't have slept long. You were fast asleep and I was certain I stumbled to bed after you, although I couldn't remember when. The hallway danced around me as I walked. I had been drinking.\n\nLisa stilled eventually. I rocked her on the porch, staring out over the pond, waiting for a glint of dawn in the water. It was brisk, but I was sweating. My dream had returned to me. Not all at once, it bubbled up first as sensations- anxiety, guilt, disgust. They blended so easily with the backdrop of my mind that I didn't pause to consider them.\n\nWhen the root of the matter made itself known I was caught by surprise. It was the kind of mean thought that provoked a visceral reaction. Like touching a hot stove, or stubbing a toe, or getting punched in the face. It was the kind of hurt that made you mad. I spat it out like a bad taste.\n\nBut it came back to settle over me. On my chest Lisa was writhing and beginning to squall again her senseless frustration. I placed a hand over her head. I wondered if she could hear my racing heartbeat.\n\nA fungus that colonized in soft tissue. It grew rapidly, ravaging its host, eating away at it and replacing what it took with a lesser copy, with a changeling. Not a threat to humans, not in normal circumstances. But deposited directly on a mucous membrane perhaps? By an irresponsible father with dirty hands wiping the nose of a bawling infant?\n\nI pushed the thought away violently. I was immediately ashamed to have even thought it. It was crass, it was a tasteless joke at a funeral. But it returned to me again.\n\nRemember the metro station back near our old house? We rode the train everywhere before we moved out to the summer house and had to surrender ourselves to car ownership.\n\nWhile we stood waiting for it to arrive, did you ever have thoughts spring to your mind of just how easily you could push the man or woman or child waiting beside you onto the tracks, just as the train screeched up to the platform? It's nothing to be ashamed of, they're automatic thoughts, easy to ignore. That is, unless you let them scare you. If they get to you then your mind will fixate on them, pick at them like a dirty fingernail at a scab - and once it's drawn blood, it's impossible to say when or if it'll let up.\n\nsample10.jek\n\nblood",
		unlocks: "sample10.jek",
		key: "nightmare",
		earnedKey: "blood",
	},
	{
		type: "game",
		name: "sample10.jek",
		unlocks: "rabbits.txt",
		key: "blood",
		earnedKey: "white",
	},
	{
		type: "text",
		name: "rabbits.txt",
		text: "I didn't go back to sleep that night. I sat on the porch with Lisa, swatting at my thoughts like biting flies, until the croaking of the frogs gave way to the birdsong of morning. Then I climbed our stairs and tucked Lisa into the crib in our bedroom. I could sense that you were awake, but you didn't speak and neither did I.\n\nI made coffee, but you didn't come downstairs. I tried to watch TV but I couldn't make sense of the conversations on the screen. Finally I rose and grabbed my keys off the counter. As I passed through the kitchen I poured the half carton of milk down the drain.\n\nI returned 40 minutes later with a fresh carton in hand. I might as well have not bothered; you still hadn't come downstairs. In the back of my truck were five live-release rabbit traps.\n\nsample11.jek\n\nrevive",
		unlocks: "sample11.jek",
		key: "white",
		earnedKey: "revive",
	},
	{
		type: "game",
		name: "sample11.jek",
		unlocks: "research.txt",
		key: "revive",
		earnedKey: "red",
	},
	{
		type: "text",
		name: "research.txt",
		text: "Infecting the rabbits with Paraisaria pandora proved a greater challenge than it had been with the tadpoles. The first problem was the question of delivery. Simply introducing the fungus to their environment likely would not be adequate, and I did not have the patience to endure failed trials. Questions burned in my mind like embers. I couldn't sleep. I couldn't eat. On the rare occasions you'd speak I couldn't focus long enough to formulate a reply. During long doctor's visits my mind drifted back to the five white rabbits in our basement, to the theory I could not confess.\n\nIn the end I immobilized them with a snare, then applied a solution containing the fungus to their eyes with a dropper.\n\nThe next question was how to ensure the infection took hold. The tadpoles succumbed to infection only after being stunned and brought close to death. I researched an array of poisons, but decided instead to make a deep incision along each rabbit's flank and to leave it open until it festered, with the hope that, fevered from bacterial infection, the rabbits would be vulnerable enough for the experiment to succeed.\n\nI worked at night, of course, after you'd gone to bed. I couldn't risk any noise making its way up the stairwell. This was about the time I installed the lock on the basement door, an event I'm sure you'll remember.\n\nsample12.jek\n\npositive",
		unlocks: "sample12.jek",
		key: "red",
		earnedKey: "positive",
	},
	{
		type: "game",
		name: "sample12.jek",
		unlocks: "apology.txt",
		key: "positive",
		earnedKey: "late",
	},
	{
		type: "text",
		name: "apology.txt",
		text: "I have to stop here for a moment. Anna... I'm sitting here at my desk, on the same worn stool you're likely sitting on as you read this, and agonizing over every word I've written. This last note was the worst.\n\nI cringe as I reread it for the hundredth time. It's not an effect of remembering the acts of violence. I've done much worse, things that unfortunately I must also spell out for you here in time. Instead, my skin crawls at the thought of your horror as you learn about the things that took place beneath your feet. I slept beside you the night after I cut the rabbits. Things weren't so cold between us then. We still touched, we made love, on occasion we would laugh.\n\nBut I have to remind myself the woman I'm confessing to isn't that same woman I knew, the woman who trusted and loved me. It's strange how we can hold two opposite beliefs at once, each as unshakeable as it is incompatible to the other. I'm so sorry I kept the truth from that woman, that I allowed the secrets and lies to build up between us until we couldn't recognize each other through their bulk. But I'm so grateful she never had to know the truth.\n\nDecades have passed. You're not that same woman. You don't trust me. Whatever I tell you now, you've likely already imagined worse. I have to remind myself of that now and then. I spend so much time in the past it's easy to imagine some road to that other woman still exists.\n\nBut she's gone. I'm sorry.\n\nsample13.jek\n\nlittle",
		unlocks: "sample13.jek",
		key: "late",
		earnedKey: "little",
	},
	{
		type: "game",
		name: "sample13.jek",
		unlocks: "results.txt",
		key: "little",
		earnedKey: "positive",
	},
	{
		type: "text",
		name: "results.txt",
		text: "The next night, after my attempt at infecting the rabbits, I found them curled in a pile in their cage. Their white fur was smeared with blood, but they were all breathing. I suspected convulsions had reopened their wounds. In hindsight what I saw was likely discharge from their eyes or nostrils. The next night I checked on them again, and cleaned and stitched their incisions. I didn't want them to die.\n\nThe months that followed were bad. We saw countless doctors. We spent days and nights in hospitals. We travelled and researched. I called every academic contact I had who'd still take my calls, who might have some clue that could lead us to an explanation, to a different explanation. Lisa was beginning to struggle to swallow. During the day I was exhausted. Sometimes I would hear you crying from another room. At night I worked in the basement.\n\nAfter 98 days the rabbits died. They had grown accustomed to my presence and some nights I'd feed them from my hand. When I saw them stiff and motionless in their cage it stopped me in my tracks for a moment. But then I set to the dissection.\n\nThis time I knew what I was looking for. It was impossible, categorically. It was the fevered dream of an overburdened mind. The sick fantasy of a conscience looking to replace grief with guilt. But I found it.\n\nOne at a time I perforated the orbital bone of each rabbit with a screwdriver. Then, using a small hooked wire, I snagged and withdrew a sample. It came easily, the soft and spongy tissue was already crumbling. As I pulled out the wire the rabbit's socket continued to ooze, as if I'd pulled out a stopper.\n\nRecalling it now, I'm surprised at how calm I was. I repeated the process with each rabbit, confirming the results each time. I spread the jellied tissue on a slide and observed it under the microscope. It resembled brain tissue, down to the branching connections that mimicked the networking of neurons, but it was unmistakably Paraisaria pandora.\n\nsample14.txt\n\nbreak",
		unlocks: "sample14.jek",
		key: "positive",
		earnedKey: "break",
	},
	{
		type: "game",
		name: "sample14.jek",
		unlocks: "flight.txt",
		key: "break",
		earnedKey: "truth",
	},
	{
		type: "text",
		name: "flight.txt",
		text: "I had found the answer I had searched for. The impossible was true. I had reached into my nightmare and dragged it into reality. The proof of it was smeared on my shaking hands.\n\nThe colony's behavior was more intricate than simply mimicking structure. The rabbits had survived months. The infection had adapted to reproduce ion gateways, to pass along electrical charges, had networked with the nervous system of the rabbits, maintaining their autonomous processes long after brain death.\n\nI wished I had observed their behavior more closely. I wished I had performed a pre-mortem dissection. I wished I had tested specimens of different sizes and species and ages.\n\nI had ten thousand burning questions, but none of them mattered. There was nothing I could do. Lisa was either infected or she wasn't. Either she was already dead, or she soon would be. I couldn't even tell you what I knew. You'd think I was mad, or cruel.\n\nBut I couldn't hide it from you, either. At some point her body would progress to complete rejection. Doctors would be able to identify the faulty immune response, the breakdown of neurological tissue, would find the oozing black and green slop where her brain should be. I wouldn't be able to lie to you then. You'd see it on me instantly. You would know that I had known.\n\nOr, she was just sick, born with some undiagnosable wasting disorder. It's not like our doctors didn't have theories. They had dozens. These things happen. We would care for her as she grew weaker, and eventually passed away. One way or the other, she'd be gone.\n\nSo it was pointless.\n\nBut when I emerged from the basement, numb, sick, and reeling, and climbed up the stairs to see you sleeping with Lisa in your arms, I couldn't bring myself to get into bed beside you. We hadn't really spoken in days. In the daylight we passed each other with downcast eyes, mumbled reminders of appointments or chores. I couldn't face you, your eyes were too filled with sadness and wounded trust. But in the darkness I met your gaze. You were asleep, your eyes were closed, but I felt your stare pierce me, angry and accusing. I felt your rage, your hatred. I accepted it, and then I left you two to return to the basement.\n\nsample15.jek\n\nquest",
		unlocks: "sample15.jek",
		key: "truth",
		earnedKey: "quest",
	},
	{
		type: "game",
		name: "sample15.jek",
		unlocks: "revelations.txt",
		key: "quest",
		earnedKey: "excavation",
	},
	{
		type: "text",
		name: "revelations.txt",
		text: "I won't enumerate all of the crimes I committed in my quest to gain answers. If you need a full accounting of them they can be excavated from the yard. An impulse drove me out into the thicket earlier today, I suppose to make a final apology, but I couldn't find any sign of them. It was decades ago, and I made my countless staggering trips in the dead of night. They're likely scattered about all over the lot.\n\nBut suffice it to say I was able to learn a few things. And for better or worse, that knowledge led us to where we are today. Sometimes I tell myself I never really had a choice, once I learned what I had to do there was never really any other option.\n\nI learned that Paraisaria pandora is able to consume and replicate a variety of soft tissues, but that each infection targets only a single type of cell. As it consumes and grows into the tissue's place it attempts to replicate its structure down to its surface proteins, which allows it to fool an organism's defenses - at least for a time.\n\nI learned that the fidelity of the replication scales proportionally to the amount of tissue consumed, and thus larger colonies can exist for a longer time frame before collapsing. After a series of tests I was able to predict with precision what this time frame would be based off of the mass of infected tissue.\n\nMy most important discovery was born of an instance of accidental cross-contamination. I failed to sanitize a scalpel after using it to excise a fungal colony for inspection, and as a result inadvertently reintroduced the sample to a test rat. The infection, having already adapted itself to the internal environment of Rattus norvegicus survived almost twice as long as my data predicted before its collapse.\n\nThe implications of this horrified me. Because of my sloppy handling of samples there was the potential any of my data could be polluted. I believed this was the first instance of cross-contamination, but I couldn't be certain. I had kept all of the excised samples. Some I had frozen, others I returned to solution for observation. In a fit of pique I determined all but the original test sample should be destroyed.\n\nsample16.jek\n\ncontamination",
		unlocks: "sample16.jek",
		key: "excavation",
		earnedKey: "contamination",
	},
	{
		type: "game",
		name: "sample16.jek",
		unlocks: "mutation.txt",
		key: "contamination",
		earnedKey: "antibody",
	},
	{
		type: "text",
		name: "mutation.txt",
		text: "I hadn't previously made an attempt at disposing of Paraisaria pandora. Pouring it down the drain would be irresponsible and it survived freezing and thawing. I supposed heat would be effective but I didn't want to risk aerosolizing colony particulate. In the end I grabbed a box of powdered herbicide from your gardening equipment and tapped a healthy portion into each sample.\n\nA moment later the box fell from my fingers. I watched for a heartbeat and then ran to get a camera. I knew my memory wouldn't be sufficient. I would force myself to rewatch the phenomenon later to ensure I could believe it. I couldn't afford to begin doubting my sanity.\n\nIn a dozen murky sample jars scattered across my desk thick ropy tendrils thrashed and writhed violently. Water splashed from the surface of one as the glass jar jerked and threatened to tip. I thought to reach for it but was too afraid to step closer. No motion could more clearly communicate pain and rage. It lasted five or ten minutes before the fibrous mossy growths calmed and soothed to an occasional twitch.\n\nI approached the desk carefully. In my head an image played out of the jars tipping, of slimy green tendrils leaping out at me, grasping me, invading my eyes and nose and mouth. But the jars remained motionless. With a shaking hand I collected the samples and sealed them, then placed them in the locked drawer of my desk. Before sealing the last jar, I excised a small piece of tissue from a motionless floating mass and prepared a slide.\n\nViewing the tissue under magnification was disorienting. The fungal cells were clearly still alive, but changed. They had survived their exposure to the herbicide, but had altered their structure radically to do so. My thoughts went to micro evolution, to organisms developing resistance to pesticides and antibiotics. There was precedent - but in an instant, from a single exposure?\n\nsample17.jek\n\ncatch",
		unlocks: "sample17.jek",
		key: "antibody",
		earnedKey: "catch",
	},
	{
		type: "game",
		name: "sample17.jek",
		unlocks: "deadline.txt",
		key: "catch",
		earnedKey: "cowardice",
	},
	{
		type: "text",
		name: "deadline.txt",
		text: "I've never been a skilled liar, Anna. It's because at my core, I'm a coward. My fear fills me up until you can see it through my eyes and mouth and it gives me away at once. And so I lied to you as little as I could and in the fashion of a coward I hid from you instead, answering any questions with short non-answers before fleeing back to the basement. I'm certain you saw through it, but I suppose you assumed I was simply hiding my drinking.\n\nThat was good enough. I wanted to tell you the truth, but you must understand why I couldn't. The stakes were too high. The knowledge I bore was too painful, too mean, too unbelievable. And afterall, I had no proof it was true. Lisa could have just as easily simply been ill. It would have been pointless and cruel to taint what would likely be your last days with her with that knowledge.\n\nEvery time I watched you hold her, every time I fed her or changed her or felt her in my arms, every time she squawked or cried, all I could think of was a ticking clock. That was the worst part, the knowledge whose burden made it impossible for me to look you in the eyes for fear that you'd read it from them. With an estimate of brain volume and some napkin math I knew roughly the moment she would die, within the day at least. I couldn't bear for you to know as well.\n\nI should rephrase. It's pedantic, but this is uncharted territory and its important I set the right foundations before moving further. I knew the day on which I would either learn that she was not infected, or that she was already dead.\n\nsample18.jek\n\nlies",
		unlocks: "sample18.jek",
		key: "cowardice",
		earnedKey: "lies",
	},
	{
		type: "game",
		name: "sample18.jek",
		unlocks: "decision.txt",
		key: "lies",
		earnedKey: "infected",
	},
	{
		type: "text",
		name: "decision.txt",
		text: "It was an important question. Was Lisa infected or not? Either way, our daughter was gone, but it mattered because I had made a decision.\n\nThe days had ticked by, day by agonizing day. Lisa's condition had not radically changed, but from my tests I knew the final collapse would be sudden and instantaneous. One moment she would be with us and in the next she would be gone. Her gradual deterioration was already somewhat of an anomaly, but I supposed that the human brain is a more intricate machine than a rabbit's.\n\nI was lying awake in bed when the idea occurred to me. I was sweaty and dry-mouthed and trying desperately to clear my mind of the thoughts that prodded me. And then the idea was just there, horrible and obvious. Looking back I think that I had decided I would try it the moment it occurred to me. Or not decided - I hadn't decided, I had simply known that I would do it, that I didn't have any choice. The subsequent agonizing was more of a formality, my rational mind's attempt to pretend it was still in control.\n\nsample19.jek\n\nrational",
		unlocks: "sample19.jek",
		key: "infected",
		earnedKey: "rational",
	},
	{
		type: "game",
		name: "sample19.jek",
		unlocks: "risk.txt",
		key: "rational",
		earnedKey: "powder",
	},
	{
		type: "text",
		name: "risk.txt",
		text: "My hands shake as I type this, just as they did that morning. I remember just how I felt. The nauseating fear, my deadened limbs working mechanically, numb fingers turning the knob of the burner, the sweet smell of warming formula. The sensations are as well preserved as any from my memories, the result of the hard practice of a thousand nightmares.\n\nI can't ask you to forgive me, Anna. I'm guilty. I've lived as much of my sentence as I can. Now I'm guilty twice for passing my punishment down to you.\n\nParaisaria pandora changed when I tried to kill it. Its cellular structure fundamentally altered, mutated. In an instant I had shunted the colony down an evolutionary pathway, one that allowed it to survive.\n\nI pulled a crumpled ziploc bag from my pocket and spooned a portion of white powder out of it into the warming formula, then stirred it in. Then I crammed the bag back into my jeans pocket, careful not to leave any white powder visible on my hands or clothes.\n\nYou were in the living room, your view of the kitchen obscured. Lisa was with you, laying on a blanket surrounded by an audience of untouched toys. I struggled to breathe evenly. I was certain you'd hear my shallow and labored breaths, that you'd guess everything and come charging in, the protective mother.\n\nIf Paraisaria pandora could change itself, its very makeup, then it could fool the immune system. It could hide. At the very least it could reset the clock. I hadn't tested the idea. There hadn't been time. There were dozens of reasons why it might not work, but it provided a chance where previously there was none, and that alone meant I had to try and bear whatever costs came of it.\n\nI returned with the bottle. I held Lisa in my arms and offered it to her. She suckled, then cried in protest, her face twisted. I suppose it tasted bitter. But I offered the bottle again, and because she trusted me, she continued to drink.\n\nThen the screaming began. It was unlike any cry we'd heard from her before. It was piercing and wild and thick with pain. You roused instantly and took her from me. She was red, and she writhed as she screamed, tiny curled fists beating senselessly. The scream was so loud it felt like a danger itself, that it might split her open as it burst out.\n\nI thank god your eyes were trained on her then, instead of me. You would have seen the guilt on me instantly. I stood helplessly over you as you tried to soothe her. I reached out but I couldn't even touch you, you would have felt the betrayal through my fingers. I reeked of it.\n\nI don't know if you noticed when I left, when I fled down the stairs. Another moment and I would have broken down. I would have confessed everything, sobbing and begging for forgiveness. We couldn't afford that, and so I left. I could hear the screams from the basement. Muffled and distorted they sounded even more monstrous.\n\nsample20.jek\n\nscream",
		unlocks: "sample20.jek",
		key: "powder",
		earnedKey: "scream",
	},
	{
		type: "game",
		name: "sample20.jek",
		unlocks: "infection.txt",
		key: "scream",
		earnedKey: "breakfast",
	},
	{
		type: "text",
		name: "infection.txt",
		text: "I don't know how long the screaming lasted while I waited in the basement. At first I tried to ignore it, then drown it out with music, finally I sought oblivion in my tried and true fashion. I awoke in the night to silence, sprawled on the floor by my desk. The events of the day felt like a dream, and I tried to believe they were. When I awoke again, it was morning.\n\nI could hear that you were awake from the sounds that drifted down the basement steps. I heard footsteps, and the low murmur of the television set, and then I heard something I hadn't heard in weeks. You were laughing.\n\nI took time to pick up the shards of the day before, to fit them back in order, and to compose myself. I could smell eggs and toast. You had made breakfast.\n\nWhen I emerged you were in the living room, bouncing Lisa on your knee. You were flush and smiling. When you heard the basement door open you called for me to come and see. Lisa was flushed as well, and squealing with delight. Her hands were clenched around the sleeves of your shirt, holding you tight as you bounced her, and she was giggling.\n\nThere are moments that can echo through a relationship for years, for a lifetime, unnamed but fundamental to everything that comes next. Your expression was bright with bewilderment and joy as I entered the room. You turned to me, holding Lisa out in your arms. And then in the space of a moment your face flattened, hardened. You lowered Lisa back to your lap and wrapped your arms around her. I don't know what you saw on me before I plastered on my smile, in the moment when the full implications of her recovery shuddered through me, but I knew instantly that you'd never forget it, not really. That half a second of undisguised emotion would form a crack between us that could never be plastered over.\n\nsample21.jek\n\ntrust",
		unlocks: "sample21.jek",
		key: "breakfast",
		earnedKey: "trust",
	},
	{
		type: "game",
		name: "sample21.jek",
		unlocks: "recovery.txt",
		key: "trust",
		earnedKey: "babbling",
	},
	{
		type: "text",
		name: "recovery.txt",
		text: "The change in Lisa was enormous. She began babbling again. Her hands and feet strengthened and only three weeks later she took her first step. The doctors couldn't explain it. They warned us to keep an eye out for returning symptoms, but acknowledged that by all signs we had a healthy baby girl.\n\nYou had your daughter back, but I lived the next months in a state of constant emotional confusion. Lisa was our healthy, beautiful daughter again. She was happy. She was quickly catching up with all the important developmental milestones. She would smile at me and my heart would swell to burst.\n\nBut then I would remember white clumps of herbicide dissolving into formula, ann anxious night with a sick infant, a bloody nose. This wasn't my daughter. Her recovery proved that. This wasn't even human. This thing had killed my daughter, had eaten her. My vision would narrow. I'd see the writhing mass of fibrous goo hiding inside her perfect velvety head.\n\nAnd then I'd hear her laugh, she'd squeeze my hand, she'd pull me back into the moment. I knew that my feelings towards her were biological, that evolutionary instinct compelled my affection for her, that rationally I should hate this alien creature masquerading as my daughter. But knowing this didn't free me from its effect. My love for her is a trap that I've always been hopeless to escape.\n\nsample22.jek\n\ntrap",
		unlocks: "sample22.jek",
		key: "babbling",
		earnedKey: "trap",
	},
	{
		type: "game",
		name: "sample22.jek",
		unlocks: "daughter.txt",
		key: "trap",
		earnedKey: "mother",
	},
	{
		type: "text",
		name: "daughter.txt",
		text: "Do you remember the morning Lisa said her first words? I was making tea and you were sitting with her in your lap, reading her a story while she played with your fingers. You reached the part in the story where the little bird finds his mother and stopped to prompt her “Can you say ma-ma?” And for the first time, without looking up from your fingers, Lisa responded.\n\nYou gasped. Our eyes met and we shared a moment of excitement. You prompted her again, and again she mumbled the words, to a cheer of praise from both of us. She noticed your excitement and started to laugh, she was in on the joke now and she repeated the word for us again and again.\n\nIt was fascinating to watch. I suppose every father has felt that way to an extent, when the tiny crying creature they've spent months caring for begins suddenly to communicate with them, to become real. But I think it was doubly so for me. I wasn't just observing a new life learning to reach out to those around her. Lisa was a whole new form of life. We were making first contact with an intelligent species. Likely the only one of her kind, an abomination born of a tragic freak accident, but nevertheless it was a singular moment in human history - our first moment of communication with something other than ourselves.\n\nLisa was something other than human. I knew that, but with every moment like this one it became harder for me to believe.\n\nEarly in her recovery I had found myself ambushed at times by a persistent suspicion. Paraisaria pandora was capable of some form of intelligence - the fact that Lisa was alive was proof of that. Was it possible that it was also aware of its own nature? Lisa gave every indication she was a burgeoning new life introducing herself to the world with boundless innocence and naivete, but what if she had some memory of her previous form? What if she wasn't molded by circumstance out of her conscious control into the hopeful and innocent life we were caring for, but instead was mimicking it deliberately? What if she was tricking us?\n\nLuckily for Lisa, the human mind has a limited capacity for bewilderment. When assaulted by too many points of astonishment to resolve at once it will simply begin to drop them, to cling to the most important and let all others roll off like rain. Each time Lisa shocked me with her joy, her laughter, her words, her love, she crowded out a bit of fear, until the only belief I had the capacity for was that she was my daughter, and that I loved her.\n\nsample23.jek\n\ntrick",
		unlocks: "sample23.jek",
		key: "mother",
		earnedKey: "trick",
	},
	{
		type: "game",
		name: "sample23.jek",
		unlocks: "growing_up.txt",
		key: "trick",
		earnedKey: "contradiction",
	},
	{
		type: "text",
		name: "growing_up.txt",
		text: "In the following months I successfully managed to convince myself of two contradictory ideas. This is a marvelous ability, and I owe to it some of the happiest years of our lives.\n\nThe first belief was that I had saved Lisa's life. Without my intervention she would have surely died, and so all of my actions leading up to that point were justified. The nights you spent alone, my secret experiments, two spoonfuls of white powder dissolving in formula… all of it had to be done so that Lisa could live.\n\nAnd after absolving myself, I was strong enough to ask you for forgiveness. Not for all of it, of course, I never told you all of it, but what you knew was enough. We started seeing Dr. Janson. I stopped drinking.\n\nI knew you didn't forgive me, but that was ok. We had time now, because of me. Because I had saved us, I could apologize for everything, I could take all your blame and anger, and in time everything would be alright again.\n\nThe second belief was that Lisa was a perfectly normal human girl. Months went by, then years. Lisa was normal in every way one could observe. She went to kindergarten, she made friends, she had imaginary tea parties and temper tantrums and birthdays. She was clever, but not outstanding, nothing to set her noticeably apart from the other boys and girls. She didn't leave a single foothold for my theory to cling to.\n\nIn the meantime the hulking shadow of that bad year receded. The doctors visits, the hours spent in the basement, the hurt and worry and fear, it all shrank as it grew distant, contracting until it felt like the memory of a nightmare, a wound my mind was eager to scab over and forget. It was surprisingly easy to convince myself the worst parts hadn't happened, or that I had been confused, that the foggy memories were a product of grief sickened dreams and alcohol.\n\nIn the basement there was a safe containing photographs, copies of the data I collected, and jars full of mouldering samples, but it was the simplest thing in the world to just not look at them, to allow it all to slip out of my mind.\n\nAnd so I rebuilt myself around these two beliefs, never considering them too closely, but allowing them to form the foundation of our new life. And it might have worked, if Lisa hadn't become sick again.\n\nsample24.jek\n\ninterest",
		unlocks: "sample24.jek",
		key: "contradiction",
		earnedKey: "interest",
	},
	{
		type: "game",
		name: "sample24.jek",
		unlocks: "sickness.txt",
		key: "interest",
		earnedKey: "cruelty",
	},
	{
		type: "text",
		name: "sickness.txt",
		text: "The sickness was crueler this time, because she was old enough to tell us she was hurting. It started as irritability. She would become confused and lash out or break down unexpectedly into tears, unable to verbalize exactly why. Her grades plummeted. She started to spend more time at home, neglecting her friends.\n\nThe memories of her first brush with sickness rushed back like fresh blood from a split stitch. We brought her to see a doctor, who after a few visits provided us a half-hearted theory of attention and mood disorders compounded by teenage angst. It was exactly like last time, vague useless theories bandied about while she continued to grow worse. We took her to another doctor, and then another.\n\nI didn't realize how fragile my peaceful existence was until it was crashing down around me. Even so, it would have been so easy to do nothing. To ignore all the signs, to remain in denial as the foundations of my life crumbled. I had buried the truth so deep and the cost of digging it back up was so great. Everything I had gained, that was the cost: my daughter and my family.\n\nBut if I did nothing, I knew what would happen. Lisa would continue to get worse. Neurological functions would decay as her immune system finally rooted out the trespasser that had been hiding within her all these years. We would watch it all happen again, slowly at first, and then one day a sudden rejection, and then death.\n\nsample25.jek\n\nrejection",
		unlocks: "sample25.jek",
		key: "cruelty",
		earnedKey: "rejection",
	},
	{
		type: "game",
		name: "sample25.jek",
		unlocks: "no_return.txt",
		key: "rejection",
		earnedKey: "inevitable",
	},
	{
		type: "text",
		name: "no_return.txt",
		text: "I would not let it happen. Whatever it took, whatever I had to sacrifice, I would keep her alive.\n\nI forced myself to return to the basement, to unlock my safe and pull out photographs and lifeless dried up samples, to look at them and remember. To remember the nights spent experimenting, the sight of green fibrous tissue nestled in the skull of a rabbit like a clam in a shell, and the inevitability of each test subject's scheduled death.\n\nThe memories flooded back to me all too easily. And once they had they refused to be contained. They spilled out of their proper order, soaking into all the memories that came after, tainting them. I lost my daughter for good that day. Every hug, every joke, every laugh, was now colored with the knowledge I had tried to forget, painted over with fear and disgust.\n\nLisa was not my daughter. She never had been. My daughter was dead, and Lisa had taken her place, slipped seamlessly into the hole she had left. She'd taken her personality, her feelings, what few memories she had, but she was something new, something different. God help me, I still loved her, but a connection was severed that I'd never be able to repair. This was what it cost to keep her alive.\n\nSo I made another plan. I waited for a day you were out of town visiting a gallery. You were gone for less than 24 hours, but that would be enough time. Lisa was flipping through channels on the television and I set a plate of eggs in front of her. Later I was meant to drive her to school, but first came breakfast, chewed sullenly as she ignored my presence.\n\nI needed more information. I had saved her before, had guided the colony in its mutation, stalled her body's immune response. I would attempt to do this again, but I needed a sample of the colony. There was no telling how it had changed in the past years, what sort of mutations it may have made to survive. I needed to study the tissue directly.\n\nHer breakfast contained a sedative. After she was unconscious I collected her from the couch and carried her to the basement. In this moment her new status in my eyes was a blessing. I forced myself to view her as a specimen, it was the only way it would be possible for me to complete my task. I didn't realize at the time how permanent that choice would be. I'd never be able to hold her as a father again.\n\nMy tools were already arranged, my desk was cleared. It would be a quick procedure. I had practiced it multiple times in the weeks leading up to this moment.\n\nI laid her flat on my desk and arranged my lamp over her face. I waited for my hands to stop shaking, and then I inserted a thin metal spike beneath her eyelid, pressing it along the inner side of her eye. I bumped it once gently, perforating the thin bone along the upper rear of her eye socket, and then removed the spike. Next I guided a narrow lancet carefully along the same path and worked it gently in the space where her frontal lobe would have been. Finally, with an improvised forceps, I shakily drew out a sample of tissue.\n\nI cried out when I saw the green tissue, so dark it was almost black, writhing in the steel grip. I can't tell you what I felt in that moment, Anna - some combination of terror, relief, disgust, vindication. Finally, I was meeting the real Lisa. I was holding her in my hand, at least a part of her.\n\nI dropped the tissue into a prepared jar, then returned my attention to the body of our daughter. Her face was bruising, but there would be no lasting physical damage, I felt confident of that. I carried her back upstairs, then into the garage, where I buckled her into the passenger seat of the hatchback. It was late, but that would only help explain why I was speeding, why I lost control.\n\nI suppose we could have died in the crash. Perhaps that would have been better. I was pulled free with a fractured kneecap, and I've walked with this cane ever since. Lisa was battered, her face bruised, a rib cracked, but otherwise unharmed. She had no memory of anything before the crash.\n\nsample26.jek\n\ncrash",
		unlocks: "sample26.jek",
		key: "inevitable",
		earnedKey: "crash",
	},
	{
		type: "game",
		name: "sample26.jek",
		unlocks: "development.txt",
		key: "crash",
		earnedKey: "adaptation",
	},
	{
		type: "text",
		name: "development.txt",
		text: "You knew something was wrong about that crash. Of course you did. It was amazing how quickly the trust I'd earned over the years evaporated. You informed me you would drive Lisa to school from now on. That was fine by me, I was busy.\n\nI handled the sample I had taken with gloves at all times and began to wear a respirator. I also installed a plastic zippered air seal between the bottom of the stairs and the door to the house. This colony had adapted to live within a human. I couldn't take any chances.\n\nI wondered if it was still thinking as it floated in its murky solution. Was some part of Lisa trapped and senseless in the slimy tuft of green material? Was it afraid? But those weren't the questions I needed to answer.\n\nI began by exposing it to various pesticides, herbicides, and fungicides. My work was so crude then, in the beginning. I worried I would kill it, but I didn't have time to waste. This time I lacked the benefit of knowing my deadline. I watched in amazement as the blob writhed and jerked in the jar, but afterwards it didn't display the same degree of mutation.\n\nI tried bacterial infection, uv exposure, starvation, competition with rival fungi, anything I felt would stretch the colony to its adaptive potential, forcing it to change to survive.\n\nThe process was grueling and time consuming, and at the same time Lisa was deteriorating. I made progress, but it was difficult to know how much was enough. I suffered along with the colony, and I felt myself changing with it too.\n\nYou were concerned about me. I told you I'd begun working again, that I'd made a discovery and would share it with you in time. I suppose you saw through that. Lisa's concern hurt worse. I wasn't used to disappointing her. I could see that she felt the change in me, in the way I looked at her. She could feel my fear when she spoke to me, when she embraced me. I began to take my meals in the basement. When I sat with you at the table I would sometimes trail off in conversation, my gaze drawn to the blacks of Lisa's eyes where I imagined I could see the wriggling mass inside, and then we would all go uncomfortably silent.\n\nYou have to understand why I couldn't tell you this. My knowledge made it impossible for me to be her father. My fascination and terror and disgust formed a wall between us. She needed me to save her, but she needed her mother as well. She couldn't afford to lose you, so you couldn't know what she really was.\n\nsample27.jek\n\ntreatment",
		unlocks: "sample27.jek",
		key: "adaptation",
		earnedKey: "treatment",
	},
	{
		type: "game",
		name: "sample27.jek",
		unlocks: "treatment.txt",
		key: "treatment",
		earnedKey: "pump",
	},
	{
		type: "text",
		name: "treatment.txt",
		text: "Eventually, I created a treatment I felt had potential. It was simple enough to slip it into her food, and then it was just a matter of waiting. The effect was awful, just like the first time. She was sick, and in the end you insisted we take her to the hospital. While you talked with the doctor, I spent a nervous few hours in the waiting room, wondering if they'd pump her stomach and how that might affect the success of her treatment. In the future I'd need to develop a less conspicuous method of delivery.\n\nHer recovery was never as dramatic as the first time again, but she survived and that was enough. I was forced to use more subtle treatments, smaller doses delivered more frequently. The work of developing them was endless, and still she remained sickly. Day and night I researched and experimented. I became a phantom in my own house, hidden away in the basement during the day, sometimes sleeping there at night when I was at a stage in my experimentation when I couldn't risk opening the plastic seal.\n\nYou must have felt like you'd drifted back in time. In her infancy disease had been lifted from her without explanation, and so when it returned again without explanation it had a fitting sort of symmetry to it. And similarly I had disappeared from your side again, leaving you to bear the burden of supporting her alone. I hope it gives you some comfort to know the role your strength played in keeping her alive. If you had left it would have been next to impossible for me to care for her.\n\nsample28.jek\n\nfidelity",
		unlocks: "sample28.jek",
		key: "pump",
		earnedKey: "fidelity",
	},
	{
		type: "game",
		name: "sample28.jek",
		unlocks: "forever.txt",
		key: "fidelity",
		earnedKey: "health",
	},
	{
		type: "text",
		name: "forever.txt",
		text: "And so the years passed. My life had been decided for me and I've lived out my sentence. Lisa's health has ebbed and waned, but for better or worse, my efforts have kept her alive. And as long as we both lived, my work would continue.\n\nThings might have gone on this way for another decade or two, but two months ago I lost consciousness at my desk. I took myself to see a doctor and he delivered me notice of my final reprieve. Cancer would take me, and soon.\n\nI've spent the past weeks preparing. I destroyed my notes and my samples, burned all the photographs. I couldn't risk leaving behind anything that would expose the truth about Lisa to anyone but you. She deserves to live out her life ignorant of what she really is. One night I wheeled a cartful of lye out to the pond, but I couldn't bring myself to pour it in. In a way it would have been a genocide.\n\nThere wasn't too much work to be done. I've been planning for this for years. I'm sorry to say there is a sense of relief. I can die knowing I did everything I possibly could.\n\nMy work had advanced as the years went on. I had plenty of time for research and I dipped heavily into my inheritance. I consulted with an old associate who gave me just enough guidance to begin a set of trials in cross breeding and gene therapy using fresh samples of Paraisaria pandora from the pond. It took years, working in the time not devoted to keeping Lisa alive, but I managed to develop a hardier strain. I designed it with a unique, almost miraculous ability. By stalling its own development, it could produce its own irritant, autonomously triggering the mutations I'd spent my lifetime coaxing out of Lisa. An infection of this strain could last a lifetime.\n\nsample29.jek\n\nautonomous",
		unlocks: "sample29.jek",
		key: "health",
		earnedKey: "autonomous",
	},
	{
		type: "game",
		name: "sample29.jek",
		unlocks: "final_request.txt",
		key: "autonomous",
		earnedKey: "compelled",
	},
	{
		type: "text",
		name: "final_request.txt",
		text: "I've spent the bulk of my final weeks here, writing this… I suppose you could call it a confession, or a final request. I've left it for you because while my work is done, yours is just beginning.\n\nI hope by now the broad strokes of what I have to ask of you are clear. I pray that you've read all that has come before this carefully, and taken it to heart.\n\nYou must keep Lisa alive. You must care for her, and you must never tell her the truth about what she is. I know that isn't fair to ask - I've escaped my punishment and passed it on to you, but none of this has been fair from the very beginning.\n\nI told you before why I could not share this with you until the very end. You may be wondering what has changed, how I can be sure you'll be capable of being a mother to her after everything I've told you. You may also be wondering, if I've already developed a hardier strain of Paraisaria pandora, what has stopped me from deploying a permanent solution already and living out my remaining days unburdened.\n\nThe answers to these questions are at the heart of my final confession to you, and my final sacrifice. You see, my new strain of Paraisaria pandora cannot be used directly to cure Lisa. While living in a host it is capable of creating the by-products that will allow her to live without my intervention, but it cannot co-exist with the infection already within her.\n\nAnd my disconnection from her, the wall of fear and confusion between us that I was helpless to reach across even after a lifetime, it was borne of her innate otherness. I would never understand how she thinks, how it is that she can even exist. How could I? She was something entirely foreign to me, to every human that has ever lived, her every thought prompted a thousand horrible questions that I'd never be able to answer, her every emotion was an existential riddle that left me sick and afraid. I could never know what I know and be a true parent to her.\n\nBut someone who thinks the same way that she does? Someone who is like her, fundamentally? They could care for her. They could love her despite what she is.\n\nI infected you with Paraisaria pandora two weeks ago. It was simpler with this strain. I smeared a tissue sample onto your toothbrush. Eight nights ago you had a nosebleed, I saw the tissues lying in the bathroom bin. It must have been uncomfortable, and frightening. You could have told me about it, you know - even after all this time I could have been good for that, a small gesture of comfort while you felt ill. But I don't blame you for keeping it to yourself.\n\nIt took all of my restraint not to question you that first week. It would have been fascinating to learn how it felt, the transition. I watched you closely, when I could. Headaches, irritability, a moment of confusion here or there, but from what I could see it was remarkably seamless, considering the violence going on inside you. You might have confused it for a head cold.\n\nBy now the Anna I know is dead. You bled what remains of her from your nose. I suppose you could say I killed her, but it would be perhaps more accurate to say that you did.\n\nYou have all of her memories and all of her feelings. Everything that was her is in you now. But you have something new as well. You have the ability to save our daughter, and the ability to understand her, to reach out to her as one of her own.\n\nYour colony will produce a chemical that allows it to continually mutate and survive the attacks of your body's immune system. I've already confirmed that it's present in your sweat. This same chemical will keep Lisa alive. Transference is simple. A blood transfusion would be best, but any bodily fluid will do. A shared cup might suffice in a pinch, or a long embrace in a warm room. As long as you're part of her life, you should be able to sustain her.\n\nsample30.jek\n\nsustain",
		unlocks: "sample30.jek",
		key: "compelled",
		earnedKey: "sustain",
	},
	{
		type: "game",
		name: "sample30.jek",
		unlocks: "goodbye.txt",
		key: "sustain",
		earnedKey: "hope",
	},
	{
		type: "text",
		name: "goodbye.txt",
		text: "Goodbye, Anna.\n\nI'm sorry I'm not saying it in person, but the truth is you and I have never really met - and besides, I am and always have been a coward.\n\nI hope what I've told you doesn't cause you too much distress. I never gave her the chance, but I know my wife would have chosen this to save Lisa. I suppose you know that too.\n\nAs for who you are now, only you can say, but whatever else is in you, I know you love your daughter.\n\nI hope you don't resent me too much for doing what I've always done and running away. I hope this time I've left you with what you need, and that when I arrive where I'm going the Anna I loved will be waiting for me.",
		key: "hope",
	},
];

const kGameData = {
	"sample1.jek" : {
		nodes: [
			{x: 0.15, y: 0.4, size: 160, vine: true},
			{x: 0.45, y: 0.35, size: 130, vine: false},
			{x: 0.7, y: 0.55, size: 100, vine: false},
		],
		enemies: [],
		mutateDisabled: true,
		message: "Drag from one cell to another to spread the infection.",
	},

	"sample2.jek" : {
		nodes: [
			{x: 0.1, y: 0.2, size: 80, vine: false, enemy: "red"},
			{x: 0.2, y: 0.3, size: 80, vine: false},
			{x: 0.08, y: 0.35, size: 100, vine: false},
			{x: 0.57, y: 0.4, size: 80, vine: false},
			{x: 0.69, y: 0.41, size: 80, vine: false},
			{x: 0.6, y: 0.53, size: 100, vine: true},
		],
		enemies: ["red"],
		mutateDisabled: true,
	},

	"sample3.jek" : {
		nodes: [
			{x: 0.25, y: 0.3, size: 180, vine: false, enemy: "red"},
			{x: 0.65, y: 0.3, size: 180, vine: false, enemy: "red"},
			{x: 0.3, y: 0.7, size: 50, vine: true},
			{x: 0.45, y: 0.71, size: 50, vine: false},
			{x: 0.6, y: 0.73, size: 50, vine: false},
			{x: 0.69, y: 0.68, size: 50, vine: false},
		],
		enemies: ["red"],
		mutateDisabled: true,	
	},

	"sample4.jek" : {
		nodes: [
			{x: 0.15, y: 0.15, size: 100, vine: false, enemy: "red"},
			{x: 0.75, y: 0.15, size: 100, vine: false, enemy: "red"},
			{x: 0.4, y: 0.4, size: 150, vine: false},
			{x: 0.1, y: 0.7, size: 80, vine: true},
			{x: 0.18, y: 0.77, size: 80, vine: false},
			{x: 0.1, y: 0.81, size: 80, vine: false},
			{x: 0.8, y: 0.7, size: 80, vine: false},
			{x: 0.7, y: 0.77, size: 80, vine: false},
			{x: 0.83, y: 0.83, size: 80, vine: false},
		],
		enemies: ["red"],
		mutateDisabled: true,	
	},


	"sample5.jek" : {
		"nodes": [
			{"x":0.104,"y":0.20375,"size":40,"enemy":"#ee4035"},
			{"x":0.117,"y":0.62,"size":40},
			{"x":0.445,"y":0.84625,"size":40},
			{"x":0.71,"y":0.6325,"size":40,"vine":true},
			{"x":0.706,"y":0.17625,"size":40},
			{"x":0.419,"y":0.0825,"size":40},
			{"x":0.341,"y":0.355,"size":160}
		],
		"mutateDisabled": true,
		"enemies": ["#ee4035"]
	},

	"sample6.jek" : {
		"nodes":[
			{"x":0.654,"y":0.1225,"size":40},
			{"x":0.65,"y":0.1875,"size":40},
			{"x":0.709,"y":0.1375,"size":100,"vine":true},
			{"x":0.05,"y":0.1525,"size":100,"enemy":"#ee4035"},
			{"x":0.077,"y":0.38375,"size":60},
			{"x":0.155,"y":0.2875,"size":60},
			{"x":0.128,"y":0.5225,"size":60},
			{"x":0.327,"y":0.615,"size":60},
			{"x":0.485,"y":0.7225,"size":60},
			{"x":0.661,"y":0.73625,"size":100},
			{"x":0.382,"y":0.77,"size":40},
			{"x":0.153,"y":0.665,"size":120}
		],
		"mutateDisabled":true,
		"enemies":["#ee4035"]
	},

	"sample7.jek" : {
		"nodes":[
			{"x":0.08,"y":0.17625,"size":80,"enemy":"#ee4035"},
			{"x":0.24,"y":0.235,"size":40},
			{"x":0.122,"y":0.365,"size":40},
			{"x":0.267,"y":0.39,"size":100},
			{"x":0.396,"y":0.5275,"size":40,"vine":true},
			{"x":0.503,"y":0.59625,"size":100},
			{"x":0.557,"y":0.82375,"size":40},
			{"x":0.719,"y":0.62125,"size":40},
			{"x":0.683,"y":0.7775,"size":100,"enemy":"#ee4035"},
			{"x":0.407,"y":0.27875,"size":100},
			{"x":0.52,"y":0.39625,"size":100},
			{"x":0.223,"y":0.57,"size":100},
			{"x":0.328,"y":0.68125,"size":100},
			{"x":0.577,"y":0.23875,"size":40,"enemy":"#ee4035"},
			{"x":0.21,"y":0.77375,"size":40,"enemy":"#ee4035"}
		],
		"mutateDisabled":true,
		"enemies":["#ee4035"]
	},
	"sample8.jek" : {
		"nodes":[
			{"x":0.156,"y":0.13625,"size":120,"enemy":"#ee4035"},
			{"x":0.526,"y":0.5075,"size":40},
			{"x":0.54,"y":0.29875,"size":60, "enemy":"#ee4035"},
			{"x":0.149,"y":0.4125,"size":100},
			{"x":0.346,"y":0.665,"size":40},
			{"x":0.327,"y":0.36625,"size":100},
			{"x":0.158,"y":0.325,"size":40},
			{"x":0.496,"y":0.13375,"size":40},
			{"x":0.396,"y":0.22375,"size":40},
			{"x":0.663,"y":0.5,"size":100},
			{"x":0.702,"y":0.19875,"size":40},
			{"x":0.712,"y":0.37375,"size":60},
			{"x":0.54,"y":0.70125,"size":40},
			{"x":0.135,"y":0.67625,"size":80},
			{"x":0.372,"y":0.53625,"size":60},
			{"x":0.658,"y":0.7575,"size":40,"vine":true}
		],
		"mutateDisabled":true,
		"enemies": ["#ee4035"]
	},

	"sample9.jek" : {
		nodes: [
			{x: 0.1, y: 0.12, size: 180, vine: false, enemy: "red"},
			{x: 0.4, y: 0.4, size: 180, vine: false, enemy: "red"},
			{x: 0.75, y: 0.73, size: 180, vine: false, enemy: "red"},
			{x: 0.17, y: 0.45, size: 100, vine: false},
			{x: 0.51, y: 0.75, size: 100, vine: false},
			{x: 0.09, y: 0.76, size: 100, vine: true},
			{x: 0.42, y: 0.12, size: 100, vine: false},
			{x: 0.7, y: 0.55, size: 100, vine: false},
			{x: 0.8, y: 0.12, size: 100, vine: false},
		],
		enemies: ["red"],
		mutateDisabled: true,	
	},

	"sample10.jek" : {
		"nodes":[
			{"x":0.079,"y":0.775,"size":100},
			{"x":0.26,"y":0.80625,"size":40},
			{"x":0.339,"y":0.7825,"size":100,"vine":true},
			{"x":0.527,"y":0.8175,"size":40},
			{"x":0.596,"y":0.7825,"size":100},
			{"x":0.357,"y":0.62125,"size":40},
			{"x":0.226,"y":0.57375,"size":100},
			{"x":0.449,"y":0.57,"size":100},
			{"x":0.297,"y":0.345,"size":160,"enemy":"#ee4035"},
			{"x":0.108,"y":0.3075,"size":40},
			{"x":0.226,"y":0.3075,"size":40},
			{"x":0.165,"y":0.43,"size":40},
			{"x":0.513,"y":0.28875,"size":40},
			{"x":0.639,"y":0.2975,"size":40},
			{"x":0.566,"y":0.4225,"size":40},
			{"x":0.149,"y":0.13,"size":100,"enemy":"#ee4035"},
			{"x":0.346,"y":0.11625,"size":100},
			{"x":0.536,"y":0.1275,"size":100,"enemy":"#ee4035"}
		],
		"mutateDisabled":true,
		"enemies":["#ee4035"]
	},
	"sample11.jek" : {
		"nodes":[
			{"x":0.068,"y":0.13375,"size":100,"vine":true},
			{"x":0.192,"y":0.14,"size":60},
			{"x":0.113,"y":0.27125,"size":60},
			{"x":0.316,"y":0.58625,"size":100},
			{"x":0.287,"y":0.5,"size":60},
			{"x":0.415,"y":0.53625,"size":60},
			{"x":0.717,"y":0.27,"size":80},
			{"x":0.662,"y":0.1875,"size":60},
			{"x":0.662,"y":0.37125,"size":60},
			{"x":0.625,"y":0.7675,"size":80},
			{"x":0.752,"y":0.63375,"size":80},
			{"x":0.713,"y":0.77625,"size":140,"enemy":"#ee4035"},
			{"x":0.073,"y":0.73125,"size":60},
			{"x":0.415,"y":0.265,"size":60},
			{"x":0.843,"y":0.1325,"size":60}
		],
		"message" : "An organism with a healthy immune system will gradually become immune to infection. Immunity is specific to a single vine. It causes units to be weaker and eventually the death of the entire vine. Mutate a vine to decrease immunity. Vines cannot grow while mutating. The longer a vine grows the more slowly its immunity rises or falls.",
		"mutateDisabled" : false,
		"enemies":["#ee4035"]
	},
	"sample12.jek" : {"nodes":[{"x":0.42,"y":0.4075,"size":140,"vine":true},{"x":0.182,"y":0.44125,"size":80},{"x":0.693,"y":0.43625,"size":80},{"x":0.3,"y":0.25875,"size":60},{"x":0.593,"y":0.255,"size":60},{"x":0.456,"y":0.27375,"size":40},{"x":0.477,"y":0.70875,"size":40},{"x":0.593,"y":0.68875,"size":80},{"x":0.278,"y":0.69625,"size":80},{"x":0.078,"y":0.20625,"size":40,"enemy":"#ee4035"},{"x":0.861,"y":0.18875,"size":40,"enemy":"#ee4035"},{"x":0.86,"y":0.8325,"size":40,"enemy":"#ee4035"},{"x":0.096,"y":0.84375,"size":40,"enemy":"#ee4035"}],"mutateDisabled":false,"enemies":["#ee4035"]},
	"sample13.jek" : {"nodes":[{"x":0.036,"y":0.11,"size":100,"vine":true},{"x":0.204,"y":0.115,"size":60},{"x":0.164,"y":0.24625,"size":60},{"x":0.024,"y":0.31375,"size":80},{"x":0.125,"y":0.34625,"size":40},{"x":0.248,"y":0.20875,"size":40},{"x":0.724,"y":0.72125,"size":160,"enemy":"#ee4035"},{"x":0.783,"y":0.5225,"size":120,"enemy":"#ee4035"},{"x":0.495,"y":0.76625,"size":140,"enemy":"#ee4035"},{"x":0.296,"y":0.09875,"size":60},{"x":0.218,"y":0.6425,"size":80},{"x":0.368,"y":0.4425,"size":100},{"x":0.519,"y":0.3,"size":60}],"mutateDisabled":false,"enemies":["#ee4035"]},
	"sample14.jek" : {"nodes":[{"x":0.409,"y":0.4075,"size":160},{"x":0.632,"y":0.48,"size":40,"enemy":"#ee4035"},{"x":0.594,"y":0.3275,"size":40},{"x":0.466,"y":0.25125,"size":40,"enemy":"#ee4035"},{"x":0.464,"y":0.66,"size":40,"enemy":"#ee4035"},{"x":0.348,"y":0.63,"size":40},{"x":0.287,"y":0.49375,"size":40,"enemy":"#ee4035"},{"x":0.684,"y":0.6925,"size":100,"vine":true},{"x":0.197,"y":0.17625,"size":120,"vine":true},{"x":0.7,"y":0.10875,"size":120},{"x":0.126,"y":0.745,"size":120}],"mutateDisabled":false,"enemies":["#ee4035"]},
	"sample15.jek" : {"nodes":[{"x":0.125,"y":0.2725,"size":40,"vine":true},{"x":0.239,"y":0.22625,"size":40},{"x":0.371,"y":0.1825,"size":80,"enemy":"#ee4035"},{"x":0.525,"y":0.325,"size":40},{"x":0.558,"y":0.47375,"size":40},{"x":0.45,"y":0.62625,"size":80,"enemy":"#ee4035"},{"x":0.523,"y":0.83375,"size":40},{"x":0.724,"y":0.84625,"size":40},{"x":0.817,"y":0.66375,"size":60,"vine":true},{"x":0.214,"y":0.69125,"size":60},{"x":0.249,"y":0.48375,"size":60},{"x":0.374,"y":0.37875,"size":40},{"x":0.669,"y":0.28125,"size":80,"enemy":"#ee4035"},{"x":0.841,"y":0.22,"size":40},{"x":0.09,"y":0.84,"size":40}],"mutateDisabled":false,"enemies":["#ee4035"]},
	"sample16.jek" : {"nodes":[{"x":0.4,"y":0.40375,"size":140,"vine":true},{"x":0.514,"y":0.31625,"size":80},{"x":0.618,"y":0.24125,"size":60},{"x":0.727,"y":0.2425,"size":40},{"x":0.827,"y":0.24375,"size":40,"enemy":"#ee4035"},{"x":0.474,"y":0.585,"size":100},{"x":0.563,"y":0.7075,"size":80},{"x":0.687,"y":0.71125,"size":60},{"x":0.725,"y":0.61,"size":60},{"x":0.771,"y":0.5325,"size":40},{"x":0.871,"y":0.52625,"size":40},{"x":0.229,"y":0.50625,"size":140},{"x":0.167,"y":0.63625,"size":60},{"x":0.087,"y":0.72375,"size":80},{"x":0.165,"y":0.8225,"size":60},{"x":0.258,"y":0.8125,"size":40,"enemy":"#ee4035"},{"x":0.289,"y":0.2975,"size":80},{"x":0.203,"y":0.21125,"size":80},{"x":0.084,"y":0.225,"size":80},{"x":0.033,"y":0.35,"size":60,"enemy":"#ee4035"},{"x":0.322,"y":0.13875,"size":60},{"x":0.42,"y":0.13125,"size":40,"enemy":"#ee4035"}],"mutateDisabled":false,"enemies":["#ee4035"]},
	"sample17.jek" : {"nodes":[{"x":0.469,"y":0.4625,"size":40},{"x":0.542,"y":0.52875,"size":60},{"x":0.377,"y":0.37375,"size":60},{"x":0.515,"y":0.3225,"size":100},{"x":0.366,"y":0.54125,"size":100},{"x":0.261,"y":0.235,"size":80,"enemy":"#ee4035"},{"x":0.664,"y":0.64375,"size":80,"enemy":"#ee4035"},{"x":0.182,"y":0.7025,"size":140, "vine": true},{"x":0.66,"y":0.13875,"size":140,"enemy":"#ee4035"},{"x":0.192,"y":0.45875,"size":80},{"x":0.738,"y":0.45375,"size":80},{"x":0.432,"y":0.17125,"size":80},{"x":0.452,"y":0.72875,"size":100}],"mutateDisabled":false,"enemies":["#ee4035"]},
	"sample18.jek" : {"nodes":[{"x":0.11,"y":0.185,"size":80},{"x":0.111,"y":0.40625,"size":80},{"x":0.104,"y":0.655,"size":80,"enemy":"#ee4035"},{"x":0.296,"y":0.3,"size":80},{"x":0.29,"y":0.53875,"size":80},{"x":0.277,"y":0.82125,"size":80},{"x":0.441,"y":0.12125,"size":100,"enemy":"#ee4035"},{"x":0.477,"y":0.435,"size":40},{"x":0.476,"y":0.75625,"size":40,"vine":true},{"x":0.619,"y":0.2875,"size":80},{"x":0.625,"y":0.5925,"size":80},{"x":0.606,"y":0.81125,"size":80},{"x":0.835,"y":0.14875,"size":80},{"x":0.822,"y":0.40875,"size":100},{"x":0.815,"y":0.70875,"size":100,"enemy":"#ee4035"}],"mutateDisabled":false,"enemies":["#ee4035"]},
	"sample19.jek" : {"nodes":[{"x":0.459,"y":0.4525,"size":80,"enemy":"#ee4035"},{"x":0.381,"y":0.3575,"size":60,"enemy":"#ee4035"},{"x":0.349,"y":0.4775,"size":60},{"x":0.443,"y":0.61875,"size":60},{"x":0.574,"y":0.58875,"size":60},{"x":0.585,"y":0.42625,"size":60},{"x":0.489,"y":0.31375,"size":60},{"x":0.37,"y":0.14875,"size":100},{"x":0.19,"y":0.3375,"size":100},{"x":0.218,"y":0.64,"size":100},{"x":0.522,"y":0.775,"size":100},{"x":0.754,"y":0.51,"size":100},{"x":0.659,"y":0.20375,"size":100},{"x":0.888,"y":0.8925,"size":40,"vine":true}],"mutateDisabled":false,"enemies":["#ee4035"]},
	"sample20.jek" : {"nodes":[{"x":0.482,"y":0.18125,"size":60},{"x":0.458,"y":0.3625,"size":100},{"x":0.427,"y":0.58625,"size":160},{"x":0.128,"y":0.10875,"size":40,"vine":true},{"x":0.322,"y":0.14125,"size":40},{"x":0.656,"y":0.14375,"size":40},{"x":0.842,"y":0.11,"size":40,"vine":true},{"x":0.094,"y":0.8525,"size":100,"enemy":"#ee4035"},{"x":0.278,"y":0.75625,"size":120},{"x":0.621,"y":0.75875,"size":120},{"x":0.821,"y":0.83625,"size":100,"enemy":"#ee4035"},{"x":0.22,"y":0.275,"size":40},{"x":0.76,"y":0.32875,"size":40},{"x":0.124,"y":0.57,"size":100},{"x":0.778,"y":0.5675,"size":100}],"mutateDisabled":false,"enemies":["#ee4035"]},
	"sample21.jek" : {"nodes":[{"x":0.072,"y":0.16875,"size":140,"enemy":"#ee4035"},{"x":0.075,"y":0.40625,"size":80},{"x":0.249,"y":0.235,"size":80},{"x":0.777,"y":0.1375,"size":120,"enemy":"#0392cf"},{"x":0.626,"y":0.215,"size":80},{"x":0.824,"y":0.36375,"size":80},{"x":0.426,"y":0.57375,"size":140,"vine":true},{"x":0.295,"y":0.74,"size":100},{"x":0.579,"y":0.7475,"size":100},{"x":0.445,"y":0.3175,"size":60},{"x":0.644,"y":0.44,"size":60},{"x":0.283,"y":0.44,"size":80}],"mutateDisabled":false,"enemies":["#ee4035","#0392cf"]},
	"sample22.jek" : {"nodes":[{"x":0.115,"y":0.19,"size":140,"enemy":"#ee4035"},{"x":0.097,"y":0.6475,"size":160,"enemy":"#0392cf"},{"x":0.694,"y":0.16375,"size":140},{"x":0.681,"y":0.63625,"size":160,"vine":true},{"x":0.397,"y":0.40375,"size":140},{"x":0.828,"y":0.44625,"size":80},{"x":0.017,"y":0.43,"size":100},{"x":0.428,"y":0.84125,"size":100},{"x":0.413,"y":0.08125,"size":100},{"x":0.332,"y":0.3225,"size":40},{"x":0.318,"y":0.63375,"size":40},{"x":0.606,"y":0.6475,"size":40},{"x":0.618,"y":0.325,"size":40},{"x":0.268,"y":0.4625,"size":40},{"x":0.617,"y":0.47625,"size":40}],"mutateDisabled":false,"enemies":["#ee4035","#0392cf"]},
	"sample23.jek" : {"nodes":[{"x":0.431,"y":0.13625,"size":140,"enemy":"#ee4035"},{"x":0.044,"y":0.38,"size":160,"vine":true},{"x":0.764,"y":0.4175,"size":160,"enemy":"#0392cf"},{"x":0.413,"y":0.70375,"size":160,"enemy":"#f37736"},{"x":0.446,"y":0.42875,"size":100},{"x":0.233,"y":0.2025,"size":100},{"x":0.666,"y":0.2025,"size":80},{"x":0.175,"y":0.68,"size":120},{"x":0.693,"y":0.74875,"size":100},{"x":0.307,"y":0.45625,"size":40},{"x":0.642,"y":0.47,"size":40}],"mutateDisabled":false,"enemies":["#ee4035","#0392cf","#f37736"]},
	"sample24.jek" : {"nodes":[{"x":0.099,"y":0.2025,"size":60},{"x":0.096,"y":0.38125,"size":60},{"x":0.256,"y":0.3125,"size":60},{"x":0.322,"y":0.4875,"size":60},{"x":0.463,"y":0.3975,"size":80},{"x":0.516,"y":0.61,"size":60},{"x":0.727,"y":0.5325,"size":60},{"x":0.751,"y":0.75125,"size":60},{"x":0.055,"y":0.63625,"size":100,"enemy":"#ee4035"},{"x":0.28,"y":0.805,"size":100,"vine":true},{"x":0.405,"y":0.10625,"size":100,"enemy":"#0392cf"},{"x":0.651,"y":0.25625,"size":120,"enemy":"#f37736"},{"x":0.867,"y":0.61375,"size":80}],"mutateDisabled":false,"enemies":["#ee4035","#0392cf","#f37736"]},
	"sample25.jek" : {"nodes":[{"x":0.411,"y":0.3825,"size":160},{"x":0.147,"y":0.175,"size":40,"vine":true},{"x":0.839,"y":0.16375,"size":40,"enemy":"#0392cf"},{"x":0.167,"y":0.845,"size":40,"enemy":"#f37736"},{"x":0.768,"y":0.84625,"size":40,"enemy":"#fdf498"},{"x":0.475,"y":0.1625,"size":40,"enemy":"#ee4035"},{"x":0.432,"y":0.7775,"size":120},{"x":0.123,"y":0.43875,"size":100},{"x":0.773,"y":0.41875,"size":100},{"x":0.278,"y":0.24625,"size":100},{"x":0.652,"y":0.24125,"size":100},{"x":0.261,"y":0.61875,"size":100},{"x":0.644,"y":0.6225,"size":100},{"x":0.855,"y":0.7025,"size":60},{"x":0.082,"y":0.67625,"size":80},{"x":0.477,"y":0.6525,"size":40}],"mutateDisabled":false,"enemies":["#0392cf","#f37736","#fdf498","#ee4035"]},
	"sample26.jek" : {"nodes":[{"x":0.148,"y":0.3525,"size":80},{"x":0.28,"y":0.1975,"size":80},{"x":0.395,"y":0.4525,"size":80},{"x":0.612,"y":0.2875,"size":80},{"x":0.704,"y":0.53375,"size":80},{"x":0.255,"y":0.70625,"size":60,"enemy":"#0392cf"},{"x":0.404,"y":0.7425,"size":80},{"x":0.78,"y":0.36,"size":60,"enemy":"#ee4035"},{"x":0.136,"y":0.1825,"size":60,"vine":true},{"x":0.277,"y":0.825,"size":80},{"x":0.663,"y":0.8025,"size":80,"enemy":"#fdf498"},{"x":0.767,"y":0.7425,"size":40},{"x":0.804,"y":0.845,"size":60,"enemy":"#fdf498"},{"x":0.101,"y":0.545,"size":40},{"x":0.117,"y":0.6125,"size":80},{"x":0.485,"y":0.16625,"size":40,"enemy":"#ee4035"},{"x":0.726,"y":0.13,"size":80,"enemy":"#f37736"}],"mutateDisabled":false,"enemies":["#0392cf","#ee4035","#fdf498","#f37736"]},
	"sample27.jek" : {"nodes":[{"x":0.728,"y":0.0825,"size":160},{"x":0.491,"y":0.11375,"size":120},{"x":0.604,"y":0.315,"size":120},{"x":0.798,"y":0.3675,"size":120},{"x":0.048,"y":0.71875,"size":60,"vine":true},{"x":0.173,"y":0.84,"size":60,"enemy":"#ee4035"},{"x":0.171,"y":0.7075,"size":60,"enemy":"#fdf498"},{"x":0.078,"y":0.5975,"size":60},{"x":0.283,"y":0.8225,"size":60},{"x":0.169,"y":0.55125,"size":80,"enemy":"#0392cf"},{"x":0.283,"y":0.67875,"size":60,"enemy":"#f37736"},{"x":0.806,"y":0.86,"size":60},{"x":0.09,"y":0.15875,"size":60},{"x":0.266,"y":0.35625,"size":60},{"x":0.504,"y":0.605,"size":60},{"x":0.647,"y":0.73,"size":60}],"mutateDisabled":false,"enemies":["#ee4035","#fdf498","#0392cf","#f37736"]},
	"sample28.jek" : {"nodes":[{"x":0.115,"y":0.4225,"size":100,"vine":true},{"x":0.476,"y":0.425,"size":80,"enemy":"#0392cf"},{"x":0.79,"y":0.4175,"size":100,"enemy":"#fdf498"},{"x":0.272,"y":0.4125,"size":100,"enemy":"#ee4035"},{"x":0.638,"y":0.42,"size":100,"enemy":"#f37736"},{"x":0.394,"y":0.6175,"size":80},{"x":0.372,"y":0.25,"size":100},{"x":0.574,"y":0.305,"size":60},{"x":0.564,"y":0.6025,"size":80},{"x":0.186,"y":0.2275,"size":100},{"x":0.202,"y":0.65,"size":80},{"x":0.733,"y":0.255,"size":60},{"x":0.726,"y":0.65875,"size":80},{"x":0.023,"y":0.25,"size":100},{"x":0.019,"y":0.57375,"size":100},{"x":0.35,"y":0.8725,"size":40},{"x":0.654,"y":0.1675,"size":40},{"x":0.301,"y":0.11125,"size":40},{"x":0.644,"y":0.77875,"size":40},{"x":0.238,"y":0.895,"size":40,"enemy":"#0392cf"},{"x":0.195,"y":0.0925,"size":40,"enemy":"#0392cf"},{"x":0.876,"y":0.62625,"size":60},{"x":0.882,"y":0.29875,"size":60}],"mutateDisabled":false,"enemies":["#0392cf","#fdf498","#ee4035","#f37736"]},
	"sample29.jek" : {"nodes":[{"x":0.77,"y":0.7725,"size":100,"vine":true},{"x":0.235,"y":0.745,"size":80,"enemy":"#ee4035"},{"x":0.459,"y":0.445,"size":80,"enemy":"#0392cf"},{"x":0.657,"y":0.19125,"size":80,"enemy":"#ee4035"},{"x":0.109,"y":0.42375,"size":80,"enemy":"#fdf498"},{"x":0.341,"y":0.16125,"size":80,"enemy":"#f37736"},{"x":0.483,"y":0.25,"size":80},{"x":0.268,"y":0.505,"size":80},{"x":0.147,"y":0.185,"size":100},{"x":0.076,"y":0.6875,"size":80},{"x":0.327,"y":0.3425,"size":60},{"x":0.385,"y":0.8125,"size":100},{"x":0.692,"y":0.355,"size":100},{"x":0.505,"y":0.64125,"size":100},{"x":0.507,"y":0.08,"size":60},{"x":0.037,"y":0.29875,"size":60},{"x":0.607,"y":0.50625,"size":60}],"mutateDisabled":false,"enemies":["#ee4035","#0392cf","#fdf498","#f37736"]},
	"sample30.jek" : {"nodes":[{"x":0.427,"y":0.76,"size":120,"vine":true},{"x":0.211,"y":0.72375,"size":80},{"x":0.449,"y":0.5175,"size":80},{"x":0.665,"y":0.71125,"size":80},{"x":0.192,"y":0.4,"size":100},{"x":0.643,"y":0.4125,"size":100},{"x":0.059,"y":0.57875,"size":80,"enemy":"#ee4035"},{"x":0.829,"y":0.56,"size":80,"enemy":"#ee4035"},{"x":0.416,"y":0.22875,"size":120,"enemy":"#ee4035"},{"x":0.073,"y":0.3125,"size":60,"enemy":"#0392cf"},{"x":0.272,"y":0.1825,"size":60,"enemy":"#f37736"},{"x":0.677,"y":0.18625,"size":60,"enemy":"#fdf498"},{"x":0.861,"y":0.37375,"size":60,"enemy":"#0392cf"},{"x":0.439,"y":0.06125,"size":60},{"x":0.33,"y":0.615,"size":60},{"x":0.592,"y":0.61,"size":60}],"mutateDisabled":false,"enemies":["#ee4035","#0392cf","#f37736","#fdf498"]},
};  
