const kFiles = [
	{
		type: "text",
		name: "Dearest_Anna_Please_Read_Important.txt",
		unlocks: "sample1.jek",
		key: "",
		text: "My Dearest Anna,\n\nIf you are reading this, then I am already dead.\n\nGood lord, what a cliche. You probably hate that I wrote that. You're probably rolling your eyes. Are they damp, I wonder? After all that's happened, do you have tears left for me?\n\nBut enough of that, I was talking about cliches. I hope you'll forgive that one. I have quite a bit to tell you, things that I'm sorry to say will be confusing and horrible. So, perhaps lingering on a worn out old trope for a moment longer isn't such a bad way to start.\n\nAnd so I'll repeat it, I am dead. And with me I've taken all of my research. I told you many times over the years, when you were still inclined towards asking, that my work was important. That it might well be the most important work any human mind has ever been burdened with. That was true. I've told you so many lies over the years, I beg you to forgive me Anna, but that much was true.\n\nBut now my work is gone. Burned, destroyed, every last hint at my studies has been purged, except for this. I pray that you've found it and only you, that you're reading this, and that not too great a span of time has passed since my death.\n\nWhat I say next, I hope you'll take with the utmost sincerity. Not for the sake of my memory, or the love we once shared (that I still to this day hold for you, whether or not you can believe that), but for the sake of the life of our daughter, which I tell you now hangs in the balance. You must read all I've left here for you. Read it carefully, commit it to heart, and follow my instructions.\n\nThis partition contains a series of files that I've left for you. You must inspect them each, carefully and in order. Some are only text, the rest are a selection of recordings, experimental data. After viewing each you will be given a key that will allow you to open the next.\n\nI'll leave you now to view the next file, though it pains me. I've left you ten thousand times before, with less fuss, but I promise you with heartbreak each time. But the truth is we've parted for the final time already.\n\nsample1.jek\n\nbeginning",
		earnedKey: "beginning",
	},
	{
		type: "game",
		name: "sample1.jek", 
		unlocks:"Summer_1965.txt", 
		key:"beginning",
		earnedKey:"bliss",
	},
	{
		type: "text",
		name: "Summer_1965.txt",
		unlocks: "sample2.jek",
		key: "bliss",
		text: "Hi Anna,\n\nI'm glad you're still reading. I knew you would. You always had such a beautiful and curious mind. I've always loved that about you, even though it was a torment to me in the end. If your mind had been average perhaps I wouldn't have had to tell you so many lies.\n\nBut, oh yes, you're wondering what it was you just saw. That was a colony of the local fungus Paraisaria Pandora, of the family Ophiocordycipitaceae. I found the strain one evening of that first year in the summer house, while examining a slide full of pond water from the yard. I was only making sure the movers hadn't jostled anything out of alignment, but then I thought I'd get to know the local flora so I recorded a time lapse as it metabolized a crumb of an egg salad sandwich.\n\nRemember how that summer we ate egg salad sandwiches? Every day for lunch, it was an egg salad sandwich, for almost 6 weeks. You were pregnant with Lisa and what a strange craving, egg salad sandwiches. Then you gave birth and after that you said they were revolting. I don't think I've eaten an egg salad sandwich since, but the smell of them always brings me back to that summer...\n\nDo you like the name? I came up with it myself. As far as I know Paraisaria Pandora hasn't been recorded by any other human. That may be because it's rare, for all I know it exists solely in our little backyard pond, but more likely it's simply that it's unremarkable. There are millions of uncatalogued samples of aquatic specimen around the world, waiting in cupboards for science to slowly sort them out.\n\nParaisaria Pandora is unremarkable. It should be unremarkable. It's a decomposer, like all fungi. It moves by growth, an opportunistic eater that searches its environment for food, feeding primarily on algae or plant matter suspended in the water. It isn't a threat to anything with a healthy immune system under normal circumstances, no more than any of the other millions of microorganisms swimming in a glass of pond water.\n\nIts only curious trait was the pattern of its growth. As it searched the slide for resources it methodically reached out in one direction and then the next, almost intelligently, until it found something organic to metabolise. And once it did, its growth exploded. The colony expanded as it consumed until the material was gone and in its place the colony had grown into an almost mold perfect copy of the original material.\n\nParaisaria Pandora isn't unique in this trait, although the fidelity of the copy was unusually impressive. The resulting growth matched the structure of the organic material it consumed down the the cellular level. This is ultimately what inspired me to attempt my second experiment with the fungus. I collected a handful of tadpoles from the yard, stunned them in an ethanol bath, and then moved them into a solution containing Paraisaria Pandora.\n\nsample2.jek\n\nopen",
		earnedKey: "open",
	},
	{
		type: "game",
		name: "sample2.jek",
		unlocks: "dead_tadpoles.txt",
		key: "open",
		earnedKey: "frozen",
	},
	{
		type: "text",
		name: "dead_tadpoles.txt",
		unlocks: "sample3.jek",
		key: "frozen",
		text: "I left the tadpoles on my desk in the basement and then promptly forgot about them. The house was still a mess and we were in a frenzy getting everything ready for the baby.\n\nYou had labeled everything so carefully, but the movers had mixed up all our boxes, so whichever one we opened was sure not to have what we were looking for and to launch a roving hunt all through the house. One night you caught me in the hall with an aquarium full of books under one arm and a dvd player under the other and asked me what I was doing. I told you I was making a cup of coffee of course and you laughed so hard I had to drop it all to help you down to the floor.\n\nDuring the day I was settling in at the university and you were painting Lisa's room blue. That was when we still thought she was going to be a boy. From her very first day she was defying expectations.\n\nA week had passed before I thought about my little experiment again and found a spare moment to go check on it. In the dim light of the basement the jar of water had taken on a mossy green. I set it under a light and peered in. I could see the wriggling shadows of a handful of healthy tadpoles. They had apparently survived their ethanol bath and been too resilient to succumb to fungal infection. There were also a few motionless shadows, floating about at mid depth in the jar.\n\nI took a spoon and fished one of the motionless tadpoles onto a paper plate with a spoon and held it under the light. It was a dull green and covered with a wisp of fuzz. I prodded it and it broke apart, revealing a fibrous interior of uniform texture. It was at that moment I realized it wasn't a tadpole at all, but the remains of a fungal colony that had consumed a tadpole and taken on its exact shape. The tadpole had likely died quickly after being moved, providing a defenceless meal for the fungus. The detail was amazing, the colony perfectly mimicked the shape of a tadpole, down to the contours of it eyes and nostrils and the tiny filaments lining its mouth.\n\nSample3.jek\n\nstronger",
		earnedKey: "stronger",
	},
	{
		type: "game",
		name: "sample3.jek",
		unlocks: "conclusions.txt",
		key: "stronger",
		earnedKey: "taxidermy",
	},
	{
		type: "text",
		name: "conclusions.txt",
		unlocks: "sample4.jek",
		text: "I feel I must pause my story here, because at this point a conclusion may be forming in your mind, one that may find support among the notions and prejudices against me you may have formed over the years, and this is a very dangerous thing because I assure you whatever assumptions you are drawing at this point cannot possibly approach the truth, and as I wrote previously your full understanding and belief of our situation is a matter of life and death.\n\nSo I'll declare now, hopefully before the thought has caught indelible in your mind, that these small morbid experiments with tadpoles in our basement do not amount to the life's work that has stolen us from each other. I did not cloister myself away, neglecting you and Lisa as I did for decades, and yes I'll admit that that's what I've done, in order to develop some macabre form of living taxidermy. I am not mad. More important than anything else, I need you to believe that.\n\nAs you continue to read I'll provide you what proof I can that what I'm telling you is true. I've saved some scraps that I hope will lend more weight than words alone can. But for now the proof I offer is to ask you to remember back to that summer. To the time we spent together. To the moments we shared as we welcomed our baby daughter into the world.\n\nThese memories are the clearest I have, the ones I've cherished the most. I've spent countless hours examining them, turning them over like tattered photographs in my mind, alone in our basement, you and Lisa just upstairs but impossibly distant. I've lived a life accumulating few more and none as joyful. I hope you've bothered to hold onto these memories, that you can still remember us the way we were then.\n\nI can spark your memory if i must. We were deeply in love. We were the center of each other's universes. And then Lisa arrived and we orbited her together. I read aloud to you both while she gurgled in your arms. You painted me asleep with her on my chest, both of us drooling. We changed diapers and warmed bottles and repainted the nursery pink but then kept the crib in our bedroom anyways. We fretted over her first cold, and every time she cried, and one night I raced her to the doctor's office when her nose bled only to be sent home with a box of tissues.\n\nI was not a man obsessed. I was there with you. We should have had more time like that, we deserved it.\n\nsample4.jek\n\nspark",
		key: "taxidermy",
		earnedKey: "spark",
	},
	{
		type: "game",
		name: "sample4.jek",
		unlocks: "synchronized.txt",
		key: "spark",
		earnedKey: "mass",
	},
	{
		type: "text",
		name: "synchronized.txt",
		unlocks: "sample5.jek",
		key: "mass",
		text: "I'll return now to the tadpoles, reluctantly, because they do still have their part to play. I've spent so much time rehearsing the telling of this story. Sitting here at my desk, desperate to spill it out to you, while you read or paint or do I truly do not know what just a couple flights of stairs away. But instead I trudge upstairs long after you're asleep to lay wordlessly beside you. I'd rather linger longer telling the happier parts of this story, those are the parts I retell to myself on nights like these, when I can barely restrain myself from rushing upstairs and spilling it all out to you in person, a final cathartic confession in the days before my death.\n\nI wanted to tell you everything, know that. But I couldn't. Not before everything was in place. And by then it was too late.\n\nBut back to the tadpoles.\n\nDespite everything else, I did find time to repeat my tadpole experiment. Not because of any morbid fascination with the furry green bodies that resulted, but because of something strange I noticed one afternoon while penning a letter at my desk. I sat down to write, affording a quick glance to the blurry wriggling shapes in the jar under the light, and then set to work. When I looked up again, what could have been only 10 or 20 minutes later, I saw something peculiar. Every single tadpole that had moments ago been alive had risen motionless to the surface of the water.\n\nI grabbed the jar and inspected it more closely. The floating bodies were completely untouched by the fungus, their skin was still shiny and dappled. One or two twitched. I scanned the murky water and confirmed that not a single living tadpole continued to wriggle around in its depths. In a span of only a few minutes, every one of them had died.\n\nI could have chalked it up to coincidence and assumed that the tadpoles had died because of the subpar environment a jar in a basement provides. However, I had been feeding them a sliver of lettuce now and then when I thought of it, and they had all survived this long. For them to all expire at once seemed extremely unlikely.\n\nI performed the experiment 3 more times. Each time about half of the tadpoles died immediately and were consumed by my growing sample of Paraisaria Pandora, forming ghostly green simulacrum of tadpoles that floated in the cloudy water. The other half of the tadpoles survived unaffected, until exactly 26 days, 18 hours, and between 20 and 40 minutes later, at which point every remaining tadpole died simultaneously.\n\nsample5.jek\n\nmass",
		earnedKey: "curious",
	},
	{
		type: "game",
		name: "sample5.jek",
		unlocks: "inside.txt",
		key: "curious",
		earnedKey: "dissection",
	},
	{
		type: "text",
		name: "inside.txt",
		text: "The startling consistency of the phenomenon established, I couldn't resist investigating further. The evening of the conclusion of the 4th experiment I put Lisa to bed, waited until you were asleep, and then crept down to the basement with a monitor so that I could examine the freshly deceased tadpoles in privacy before the Paraisaria Pandora consumed them entirely.\n\nI fished out the small slimy corpses and laid them out lengthwise on a section of cardboard. The members of the previous rounds I had packed and sealed in our large box freezer, and now I retrieved them as well, arranging them directly below my desk lamp to thaw.\n\nThe tadpoles were of the species Lithobates palustris, the offspring of the dark spotted pickerel frogs that kept you awake so many nights that first summer with their incessant calling. I'd borrowed a reference from the university and laid it open beside me before thumbing to the page I'd marked.\n\nI began by rinsing a tadpole with distilled water and inspecting its exterior. It appeared perfectly normal, with no visible sign of fungal infection. Next I made a shallow ventral incision and pinned it, spread open, to the cardboard. I wasn't sure what I expected to see. The diagram I had available was only sufficient to identify the species and its major organs, not to determine cause of death.\n\nBut I had already attempted all other avenues to explanation. I ruled out deoxygenation or toxic buildup in the jar when I tried migrating new tadpoles to the same water after a mass die off and they thrived. I ruled out the environment of the basement as the killer by keeping an uninfected jar of tadpoles alive for over 40 days. Tadpoles uncompromised by an ethanol bath also thrived in the infected water, failing to die off on schedule. And so, the only explanation was that the colony was able to affect some physiological change on the weakened tadpoles, one that only managed to kill them after an incubation time of almost a month.\n\nI observed the swirl of intestines, the pale tissue that formed the precursor to lungs, a tiny heart that twitched intermittently. I began to doubt that I'd be able to find any visible evidence of what killed the creature. But then, as I lengthened the incision to the anterior, the scalpel suddenly released a small discharge of rust colored goo, mottled with a crumbled greenish material.\n\nI smeared a small portion of the material on a slide. Under the microscope it was clear that the material was the remains of tissue destroyed by an infection of Paraisaria Pandora. I rinsed the specimen and inspected the void where the liquified tissue had been. It seemed the colony had managed to gain a foothold in the soft tissue of the tadpole's gills, eating them away and killing it by asphyxiation.\n\nSample6.jek\n\nbreathless",
		unlocks: "sample6.jek",
		key: "dissection",
		earnedKey: "breathless",
	},
	{
		type: "game",
		name: "sample6.jek",
		unlocks: "parasite.txt",
		key: "breathless",
		earnedKey: "duplication",
	},
	{
		type: "text",
		name: "parasite.txt",
		text: "The cause of death for the tadpoles was established, infection of the soft tissues in the gills by Paraisaria Pandora. One by one I dissected each freshly deceased tadpole, and then the thawed tadpoles from the freezer for good measure. Each displayed the same damage, gills completely destroyed by fungal infection.\n\nHowever, this told me nothing to explain the original mystery, the eerie synchronicity of their deaths. If anything, it raised further questions. The damage to the gills was complete, as though they'd liquified all at once, which ruled out a gradual deterioration of the tissues by a slow moving infection. But if the colony was ravaging the tissue instantaneously, what prevented the fungus from taking hold for weeks, and what made it fail all at once?\n\nI retrieved a live tadpole from a jar, an unlucky specimen from the fifth round of my experiment. It had been 4 days since it had been immunocompromised and then introduced to an environment containing Paraisaria Pandora. I pinned it to the cardboard and made a practised incision, then pulled back the tissue to reveal the tadpole's internal gills.\n\nThe tissue appeared healthy, with no signs of damage or infection. The soft filaments were packed tightly in thousands of uniform fleshy ribs, all of them flexing and straining in tandem as the tadpole asphyxiated. The color was dark green, tinged crimson by the capillaries scaffolded by the intricate netting of flesh. Using the scalpel I pared away a sliver of the tissue and placed it carefully on a slide.\n\nI was searching for the signs of preliminary infection, and I found it immediately. The viewscope filled with the familiar latticed structure of a cluster of Paraisaria Pandora cells. I reduced magnification, expecting to see the cluster resolve into a fibrous speck nestled within the filaments of the tadpole's gills. Instead it blurred out of view and then melted into the meaty threads. I increased magnification again, panned slightly past the pulsing red of a suffocating capillary, and again found a dense cluster of fungal cells. I panned about, confirming the cluster covered significant area, and reduced magnification, but again the view blurred then resolved to an unblemished view of healthy gill tissue.\n\nI repeated the exercise multiple times before I could accept what I was observing. When presented with the unbelievable a single point of proof isn't adequate the mind requires proof in rounds, administered over time, for it to truly sink in.\n\nThere was no pocket of fungus nestled among the gill tissue, slowly eating and growing. There was no gill tissue at all. The surviving tadpoles did not fend off infection until their immune systems finally gave out weeks later. They had succumbed to infection immediately. Particles of Paraisaria Pandora lodged in the soft tissue of their gills and in their peculiar manner had exploded with growth, devouring cells and then growing into their place, quickly forming a colony that perfectly mimicked the structure of gills.\n\nIn a miraculous adaptive quirk, the fungus did not metabolize vascular tissue. Instead, it grew around it, exactly replicating the finely threaded latticework of the tadpole's gills, which supported and spread the tadpole's capillaries. In doing so, it actually replaced the tissue it consumed, the colony itself became functioning gills.\n\nThe sudden death of the tadpoles was not predicated on a overwhelmed immune system finally giving in to infection. In fact, the exact opposite was true, the tadpoles died moments after their traumatized immune system managed to reject their transplanted gills. The fungus adapted marvelously, but could only hide for so long before it was identified as foreign material, at which point blood flooded to the colony, antibodies began to break down the fungal tissue, and in a matter of moments capillaries ruptured, tissue dissolved, and the entire structure crumbled into an unbreathing mass of crimson jelly.\n\nsample7.jek\n\njelly",
		unlocks: "sample7.jek",
		key: "duplication",
		earnedKey: "jelly",
	},
	{
		type: "game",
		name: "sample7.jek",
		unlocks: "finished",
		key: "jelly",
		earnedKey: "euthanize",
	},
	{
		type: "text",
		text: "I euthanized the remaining tadpoles. The phenomenon was fascinating, but the mystery had been solved, and I found myself developing an uncomfortable empathy for the doomed creatures, a persistent scratching in my throat whenever I thought of them. So I dumped the contents of the jars back into the pond and sterilized my workstation. On a last minute impulse I sealed a sample of Paraisaria Pandora in a plastic bag and stored it away in the freezer. I had an associate in mind who might be interested in it for a future paper.\n\nAnd then I forgot about it. Our lives were full, and I deemed the experiment too grisly for dinner conversation, so I never even mentioned it to you. Life went on, happily.\n\nsample8.jek\n\nover",
		name: "finished.txt",
		unlocks: "sample8.jek",
		key: "euthanize",
		earnedKey: "over",
	},
	{
		type: "game",
		name: "sample8.jek",
		unlocks: "life.txt",
		key: "over",
		earnedKey: "time",
	},
	{
		type: "text",
		name: "life.txt",
		text: "We were so full of hope that first year. Lisa was happy and healthy, growing, babbling, crawling all over the place. You were featured in some gallery, I can't recall where now, but I can remember one piece. You painted our home, but stretched tall and gleaming white as if made from stone. On all sides it was crowded by surging brambles and vines that clung and climbed up the walls. You titled it 'Castle'. I never told you, but at the time I thought it might be a commentary on yard work.\n\nWe were so happy and it felt impossible that we wouldn't always be happy. And then everything went wrong so quickly. I lost my grant at the university. We were starting to worry about Lisa. It was a little over a year and the doctors all said she should be beginning to form words. And of course, that was the year mom died. My brother called to let me know she'd finally done it. At least the inheritance took the pressure off after I left work.\n\nIt was a lot to deal with at once, too much. Lisa stopped babbling, her hands and legs stiffened. We saw doctors, and they told us she was suffering from some neurological disorder, that with time and money we might see some improvement. You stopped painting. I had my first rough patch with drinking.\n\nLisa wasn't just delayed, she was getting worse. We could both see it, but no one could tell us why, or how to stop it. Scans came back normal and doctors recommended us to early intervention programs.\n\nsample9.jek\n\ncastle",
		unlocks: "sample9.jek",
		key: "time",
		earnedKey: "castle",
	},
	{
		type: "game",
		name: "sample9.jek",
		unlocks: "dream.txt",
		key: "castle",
		earnedKey: "nightmare",
	},
	{
		type: "text",
		name: "dream.txt",
		text: "I had a dream about the tadpoles. I don't recall how it went, but I remember waking up drenched in sweat, with the image of wriggling shadows in murky green water fading into recent memory. Lisa was crying, and my mouth was dry, so I got up. Even her cry had changed, from a healthy bawl that imposed itself on the room to a plaintive wail. I picked her up and braced her, squirming, against my shoulder, then padded toward the kitchen for a glass of water.\n\nI couldn't have slept long. You were fast asleep and I was certain I stumbled to bed after you, although I couldn't remember when. The hallway danced around me as I walked, I had been drinking.\n\nLisa settled eventually. I rocked her on the porch, staring out over the pond, waiting for a glint of dawn in the water. It was brisk, but I was sweating. My dream had returned to me. Not all at once. It bubbled up first as sensations- anxiety, guilt, terror. They blended so easily with the backdrop of mind that I didn't pause to consider them.\n\nSo when the root of the matter made itself known I was caught by surprise. It was the kind of mean thought that provoked a visceral reaction. Like touching a hot stove, or stubbing a toe, or getting punched in the face, it was the kind of hurt that made you mad. I spat it out like a bad taste.\n\nBut it came back to settle over me. On my chest Lisa was writhing and beginning to squall again her senseless frustration. I placed a hand over her head. I wondered if she could hear my racing heartbeat.\n\nA fungus that colonized in soft tissue. It grew rapidly, ravaging its host, eating away at it, and replacing what it took with a lesser copy, with a changeling. Not a threat to humans, not in normal circumstances. But deposited directly on a mucous membrane perhaps? By an irresponsible father with dirty hands wiping the nose of an infant with a cold?\n\nI pushed the thought away violently. I was immediately ashamed to have even thought it. It was crass, it was a tasteless joke at a funeral. But it returned to me again.\n\nHave you ever stood waiting for a train, and the thought springs unbidden to your mind how easily you could push the man or woman or child waiting beside you just as the train screeched up to the platform? Its an automatic thought, easy to ignore, unless you let it scare you. If it gets to you, then your mind will fixate on it, pick at it like a scab, and once it's drawn blood it's impossible to say when or if it'll let up.\n\nsample10.jek\n\nblood",
		unlocks: "sample10.jek",
		key: "nightmare",
		earnedKey: "blood",
	},
	{
		type: "game",
		name: "sample10.jek",
		unlocks: "rabbits.txt",
		key: "blood",
		earnedKey: "white",
	},
	{
		type: "text",
		name: "rabbits.txt",
		text: "I didn't go back to sleep that night. I sat on the porch with Lisa, swatting at my thoughts like biting flies, until the croaking of the frogs gave way to the birdsong of morning. Then I climbed our stairs and tucked Lisa into the crib in our bedroom. I could tell you were awake, but you didn't speak and neither did I.\n\nI made coffee, but you didn't come downstairs. I tried to watch tv but I couldn't make sense of the conversations on the screen. Finally I rose and grabbed my keys off the counter. As I passed through the kitchen I poured the half carton of milk down the drain.\n\nI returned 40 minutes later with a fresh carton in hand. I might as well have not bothered, as you still hadn't come downstairs. In the back of my truck were five live release rabbit traps.\n\nsample11.jek\n\nrevive",
		unlocks: "sample11.jek",
		key: "white",
		earnedKey: "revive",
	},
	{
		type: "game",
		name: "sample11.jek",
		unlocks: "research.txt",
		key: "revive",
		earnedKey: "red",
	},
	{
		type: "text",
		name: "research.txt",
		text: "Infecting the rabbits with Paraisaria Pandora proved a greater challenge than the tadpoles. The first problem was the question of delivery. Simply introducing the fungus to their environment likely would not be adequate, and I did not have the patience to endure failed trials. Questions burned in my mind like embers. I couldn't sleep, I couldn't eat. On the rare occasions you'd speak I couldn't focus long enough to formulate a reply. During long doctor's visits my mind drifted back to the 5 white rabbits in our basement, to the theory I could not confess.\n\nIn the end I immobilized them with a snare, and then applied a solution containing the fungus to their eyes with a dropper.\n\nThe next question was how to ensure the infection took hold. The tadpoles succumbed to infection only after being stunned and brought close to death. I researched an array of poisons, but decided instead to make a deep incision along each rabbit's flank and to leave it open until it festered, with the hope that fevered from bacterial infection the rabbits would be vulnerable enough for the experiment to succeed.\n\nI worked at night of course, after you'd gone to bed. I couldn't risk any noise making its way up the stairwell. This was about the time I installed the lock on the basement door, as I'm sure you'll remember.\n\nsample12.jek\n\npositive",
		unlocks: "sample12.jek",
		key: "red",
		earnedKey: "positive",
	},
	{
		type: "game",
		name: "sample12.jek",
		unlocks: "apology.txt",
		key: "positive",
		earnedKey: "late",
	},
	{
		type: "text",
		name: "apology.txt",
		text: "I have to stop here for a moment. Anna... I'm sitting here at my desk, on the same worn stool you're likely sitting on as you read this, and agonizing over every word I've written. This last post was the worst.\n\nI cringe as I reread for the tenth time. It's not an effect remembering the acts of violence has on me. I've done much worse, things that unfortunately I must also spell out for you here in time. Instead, my skin crawls at the thought of your horror as you learn about the things that took place beneath your feet. I slept beside you the night after I cut the rabbits. Things weren't so cold between us then. We still touched, we made love, on occasion we would laugh.\n\nBut I have to remind myself the woman I'm confessing to isn't that same woman I knew, the woman who trusted and loved me. It's strange how we can hold two opposite beliefs at once, each as unshakeable as it is incompatible to the other. I'm so sorry I kept the truth from that woman, that I allowed the secrets and lies to build between us until we couldn't recognize each other through them. But I'm so grateful she never had to know the truth.\n\nDecades have passed. You're not that same woman. You don't trust me. Whatever I tell you now, you've likely already imagined worse. I have to remind myself of that now and then, I spend so much time in the past it's easy to imagine some road to that other woman still exists.\n\nBut she's gone. I'm sorry.\n\nsample13.jek\n\nlittle",
		unlocks: "sample13.jek",
		key: "late",
		earnedKey: "little",
	},
	{
		type: "game",
		name: "sample13.jek",
		unlocks: "results.txt",
		key: "little",
		earnedKey: "positive",
	},
	{
		type: "text",
		name: "results.txt",
		text: "The next night, after my attempt at infecting the rabbits, I found them curled in a pile in their cage. Their white fur was smeared with blood, but they were all breathing. I suspected convulsions had reopened their wounds. In hindsight it was likely discharge from their eyes or nostrils. The next night I checked on them again, and cleaned and stitched their incisions. I didn't want them to die.\n\nThe months that followed were painful. We saw countless doctors, we spent days and nights in hospitals. We travelled and researched. I called every research contact I had who'd still take my calls, who might have some clue that could lead us to an explanation, to a different explanation. Lisa was beginning to struggle to swallow. During the day I was exhausted. Sometimes I would hear you crying from another room. At night I worked in the basement.\n\nAfter ninety eight days the rabbits died. They had grown accustomed to my presence and some nights I'd feed them from my hand. When I saw them stiff and motionless in their cage for a moment it stopped me in my tracks, but then I began the dissection.\n\nThis time I knew what I was looking for. It was impossible, categorically, it was the fevered dream of an overburdened mind. The sick fantasy of a conscience looking to replace grief with guilt. But there it was.\n\nOne at a time I perforated the orbital bone of each rabbit with a screwdriver. Then, using a small hooked wire, I snagged and withdrew a sample. It came easily, the soft and spongy tissue was already crumbling. As I pulled out the wire it continued to ooze out of the rabbit, as if I'd pulled out the stop.\n\nRecalling it now, I'm surprised at how calm I was. I repeated the process with each rabbit, confirming the results each time. I spread the jellied tissue on a slide and observed it under the microscope. It resembled brain tissue, down to the branching connections mimicking the networking of neurons, but it was unmistakably Paraisaria Pandora.\n\nsample14.txt\n\nbreak",
		unlocks: "sample14.jek",
		key: "positive",
		earnedKey: "break",
	},
	{
		type: "game",
		name: "sample14.jek",
		unlocks: "flight.txt",
		key: "break",
		earnedKey: "truth",
	},
	{
		type: "text",
		name: "flight.txt",
		text: "I had found the answer I'd searched for. The impossible was true. I had reached into my nightmare and dragged it into reality. The proof of it was smeared on my shaking hands.\n\nThe colony's behavior was more intricate than simply mimicking structure. The rabbits had survived months. The infection had adapted to reproduce ion gateways, to pass along electrical charges, had networked with the nervous system of the rabbits, maintaining their autonomous processes long after brain death.\n\nI wished I had observed their behavior more closely. I wished I had performed a pre mortem dissection. I wished I had tested specimens of different sizes and species and ages.\n\nI had ten thousand burning questions and none of them mattered. There was nothing I could do. Lisa was either infected or she wasn't. Either way, it seemed, she would die. I couldn't even tell you what I knew. You'd think I was mad, or cruel.\n\nI couldn't hide it from you either. At some point her body would progress to complete rejection. Doctors would be able to identify the faulty immune response, the breakdown of neurological tissue, would find the oozing black and green slop where her brain should be. I wouldn't be able to lie to you then, you'd see it on me instantly. You would know that I had known.\n\nOr, she was just sick. Some undiagnosable neurological wasting disorder, our doctors had a handful of theories. We would care for her as she grew weaker, and eventually died. Either way she'd be gone.\n\nSo it was pointless. But when I emerged from the basement, numb, sick, reeling, and climbed up the stairs to see you sleeping with Lisa in your arms, I couldn't bring myself to get into bed beside you. We hadn't really spoken in days. In the daylight we passed each other with downcast eyes, mumbled reminders of appointments or chores. I couldn't meet your gaze, your eyes were too filled with sadness and wounded trust. But in the darkness I felt your eyes on me. You were asleep, but I felt them pierce me, angry and accusing. I returned your stare, felt your rage, your hatred. I accepted it, and then I left, returning to the basement.\n\nsample15.jek\n\nquest",
		unlocks: "sample15.jek",
		key: "truth",
		earnedKey: "quest",
	},
	{
		type: "game",
		name: "sample15.jek",
		unlocks: "revelations.txt",
		key: "quest",
		earnedKey: "excavation",
	},
	{
		type: "text",
		name: "revelations.txt",
		text: "I won't enumerate all of my crimes I committed in my quest to gain answers. If you need a full accounting of them they can be excavated out back. An impulse drove me out into the thicket earlier today, I suppose for a final apology, but I couldn't find any sign of them. It was decades ago, and I made my countless staggering trips in the dead of night. They're likely scattered about everywhere.\n\nBut suffice it to say I was able to learn a few things. And for better or worse, that knowledge led us to where we are today. Sometimes I tell myself I never really had a choice, once I learned what I had to do there was never really any other option.\n\nI learned that Paraisaria pandora is able to consume and replicate a variety of soft tissues, but that each infection targets only a single type of cell. As it consumes and grows into the tissue's place it attempts to replicate it, down to its surface proteins, which allows it to fool an organism's defenses, at least for a time.\n\nI learned that the fidelity of the replication scales proportionally to the amount of tissue consumed, and thus larger colonies can exist for a longer time frame before collapsing. After a series of tests I was able to predict with precision what this time frame would be based off of the mass of infected tissue.\n\nMy final and most important discovery was born of an instance of accidental cross contamination. I failed to disinfect a scalpel after using it to excise a fungal colony for inspection, and as a result inadvertently reintroduced the sample to a test rat. The infection, having already adapted itself to the internal environment of Rattus norvegicus survived almost twice as long as my data predicted before its collapse.\n\nThe implications of this horrified me. Because of my sloppy handling of my samples there was the potential any of my data could be polluted. I believed this was the first instance of cross contamination, but I couldn't be certain. I had kept all of the excised samples, some frozen, others I returned to solution for observation. In a fit of pique I determined all but the original test sample should be destroyed.\n\nsample16.jek\n\ncontamination",
		unlocks: "sample16.jek",
		key: "excavation",
		earnedKey: "contamination",
	},
	{
		type: "game",
		name: "sample16.jek",
		unlocks: "mutation.txt",
		key: "contamination",
		earnedKey: "antibody",
	},
	{
		type: "text",
		name: "mutation.txt",
		text: "I hadn't previously made an attempt at disposing of Paraisaria pandora. Pouring it down the drain would be irresponsible and it survived thawing. I supposed heat would be effective, but I didn't want to risk aerosolizing colony particulate. In the end I grabbed a box of powdered herbicide from your gardening equipment and tapped a healthy portion into each sample.\n\nA moment later, the box fell from my fingers. I watched for a moment and then ran to get a camera. I knew my memory wouldn't be sufficient. I'd need to be able to rewatch the phenomenon to believe it. I couldn't afford to begin doubting my sanity.\n\nIn a dozen murky sample jars scattered across my desk thick ropy tendrils thrashed and writhed violently. Water splashed from the surface of one as the glass jars jerked and threatened to tip. I thought to reach for it but was too afraid to step closer. No motion could more clearly communicate pain, and rage. It lasted five or ten minutes before the fibrous mossy growths calmed, soothed to an occasional twitch.\n\nI approached the desk carefully. In my head an image played out of the jars tipping, of slimy green tendrils leaping out at me, grasping me, invading my eyes and nose and mouth. But the jars remained motionless. With a shaking hand I collected the samples and sealed them, then placed them in the locked drawer of my desk. Before sealing the last jar, I excised a small piece of tissue from a motionless floating mass and prepared a slide.\n\nViewing the tissue under magnification was disorienting. The fungal cells were clearly still alive, but radically shifted. My thoughts went to micro evolution, to organisms developing resistance to pesticides and antibiotics. There was precedent, but in an instant, from a single exposure? I had triggered Paraisaria pandora to fundamentally altered itself in a matter of moments.\n\nsample17.jek\n\ncatch",
		unlocks: "sample17.jek",
		key: "antibody",
		earnedKey: "catch",
	},
	{
		type: "game",
		name: "sample17.jek",
		unlocks: "",
		key: "catch",
		earnedKey: "",
	},
	{
		type: "game",
		name: "sample18.jek",
		unlocks: "",
		key: "catch",
		earnedKey: "",
	},
	{
		type: "game",
		name: "sample19.jek",
		unlocks: "",
		key: "catch",
		earnedKey: "",
	},
	{
		type: "game",
		name: "sample20.jek",
		unlocks: "",
		key: "catch",
		earnedKey: "",
	},
	{
		type: "game",
		name: "sample21.jek",
		unlocks: "",
		key: "catch",
		earnedKey: "",
	},
	{
		type: "game",
		name: "sample22.jek",
		unlocks: "",
		key: "catch",
		earnedKey: "",
	},
	{
		type: "game",
		name: "sample23.jek",
		unlocks: "",
		key: "catch",
		earnedKey: "",
	},
	{
		type: "game",
		name: "sample24.jek",
		unlocks: "",
		key: "catch",
		earnedKey: "",
	},
	{
		type: "game",
		name: "sample25.jek",
		unlocks: "",
		key: "catch",
		earnedKey: "",
	},
	{
		type: "game",
		name: "sample26.jek",
		unlocks: "",
		key: "catch",
		earnedKey: "",
	},
	{
		type: "game",
		name: "sample27.jek",
		unlocks: "",
		key: "catch",
		earnedKey: "",
	},
	{
		type: "game",
		name: "sample28.jek",
		unlocks: "",
		key: "catch",
		earnedKey: "",
	},
	{
		type: "game",
		name: "sample29.jek",
		unlocks: "",
		key: "catch",
		earnedKey: "",
	},
	{
		type: "game",
		name: "sample30.jek",
		unlocks: "",
		key: "catch",
		earnedKey: "",
	},
];

const kGameData = {
	"sample1.jek" : {
		nodes: [
			{x: 0.15, y: 0.4, size: 160, vine: true},
			{x: 0.45, y: 0.35, size: 130, vine: false},
			{x: 0.7, y: 0.55, size: 100, vine: false},
		],
		enemies: [],
		mutateDisabled: true,
		message: "Drag from one cell to another to spread the infection.",
	},

	"sample2.jek" : {
		nodes: [
			{x: 0.1, y: 0.2, size: 80, vine: false, enemy: "red"},
			{x: 0.2, y: 0.3, size: 80, vine: false},
			{x: 0.08, y: 0.35, size: 100, vine: false},
			{x: 0.57, y: 0.4, size: 80, vine: false},
			{x: 0.69, y: 0.41, size: 80, vine: false},
			{x: 0.6, y: 0.53, size: 100, vine: true},
		],
		enemies: ["red"],
		mutateDisabled: true,
	},

	"sample3.jek" : {
		nodes: [
			{x: 0.4, y: 0.3, size: 180, vine: false, enemy: "red"},
			{x: 0.3, y: 0.7, size: 50, vine: true},
			{x: 0.45, y: 0.71, size: 50, vine: false},
			{x: 0.6, y: 0.73, size: 50, vine: false},
			{x: 0.69, y: 0.68, size: 50, vine: false},
		],
		enemies: ["red"],
		mutateDisabled: true,	
	},

	"sample4.jek" : {
		nodes: [
			{x: 0.15, y: 0.15, size: 100, vine: false, enemy: "red"},
			{x: 0.75, y: 0.15, size: 100, vine: false, enemy: "red"},
			{x: 0.4, y: 0.4, size: 150, vine: false},
			{x: 0.1, y: 0.7, size: 80, vine: true},
			{x: 0.18, y: 0.77, size: 80, vine: false},
			{x: 0.1, y: 0.81, size: 80, vine: false},
			{x: 0.8, y: 0.7, size: 80, vine: false},
			{x: 0.7, y: 0.77, size: 80, vine: false},
			{x: 0.83, y: 0.83, size: 80, vine: false},
		],
		enemies: ["red"],
		mutateDisabled: true,	
	},


	"sample5.jek" : {
		"nodes": [
			{"x":0.104,"y":0.20375,"size":40,"enemy":"#ee4035"},
			{"x":0.117,"y":0.62,"size":40},
			{"x":0.445,"y":0.84625,"size":40},
			{"x":0.71,"y":0.6325,"size":40,"vine":true},
			{"x":0.706,"y":0.17625,"size":40},
			{"x":0.419,"y":0.0825,"size":40},
			{"x":0.341,"y":0.355,"size":160}
		],
		"mutateDisabled": true,
		"enemies": ["#ee4035"]
	},

	"sample6.jek" : {
		nodes: [
			{x: 0.1, y: 0.1, size: 180, vine: false, enemy: "red"},
			{x: 0.4, y: 0.4, size: 180, vine: false, enemy: "red"},
			{x: 0.75, y: 0.73, size: 180, vine: false, enemy: "red"},
			{x: 0.17, y: 0.45, size: 100, vine: false},
			{x: 0.51, y: 0.75, size: 100, vine: false},
			{x: 0.09, y: 0.76, size: 100, vine: true},
			{x: 0.42, y: 0.1, size: 100, vine: false},
			{x: 0.7, y: 0.55, size: 100, vine: false},
			{x: 0.8, y: 0.1, size: 100, vine: false},
		],
		enemies: ["red"],
		mutateDisabled: true,	
	},


	"sample7.jek" : {
		"nodes":[
			{"x":0.08,"y":0.17625,"size":80,"enemy":"#ee4035"},
			{"x":0.24,"y":0.235,"size":40},
			{"x":0.122,"y":0.365,"size":40},
			{"x":0.267,"y":0.39,"size":100},
			{"x":0.396,"y":0.5275,"size":40,"vine":true},
			{"x":0.503,"y":0.59625,"size":100},
			{"x":0.557,"y":0.82375,"size":40},
			{"x":0.719,"y":0.62125,"size":40},
			{"x":0.683,"y":0.7775,"size":100,"enemy":"#ee4035"},
			{"x":0.407,"y":0.27875,"size":100},
			{"x":0.52,"y":0.39625,"size":100},
			{"x":0.223,"y":0.57,"size":100},
			{"x":0.328,"y":0.68125,"size":100},
			{"x":0.577,"y":0.23875,"size":40,"enemy":"#ee4035"},
			{"x":0.21,"y":0.77375,"size":40,"enemy":"#ee4035"}
		],
		"mutateDisabled":true,
		"enemies":["#ee4035"]
	},
	"sample8.jek" : {
		"nodes":[
			{"x":0.156,"y":0.13625,"size":120,"enemy":"#ee4035"},
			{"x":0.526,"y":0.5075,"size":40},
			{"x":0.54,"y":0.29875,"size":60, "enemy":"#ee4035"},
			{"x":0.149,"y":0.4125,"size":100},
			{"x":0.346,"y":0.665,"size":40},
			{"x":0.327,"y":0.36625,"size":100},
			{"x":0.158,"y":0.325,"size":40},
			{"x":0.496,"y":0.13375,"size":40},
			{"x":0.396,"y":0.22375,"size":40},
			{"x":0.663,"y":0.5,"size":100},
			{"x":0.702,"y":0.19875,"size":40},
			{"x":0.712,"y":0.37375,"size":60},
			{"x":0.54,"y":0.70125,"size":40},
			{"x":0.135,"y":0.67625,"size":80},
			{"x":0.372,"y":0.53625,"size":60},
			{"x":0.658,"y":0.7575,"size":40,"vine":true}
		],
		"mutateDisabled":true,
		"enemies": ["#ee4035"]
	},
	"sample9.jek" : {
		"nodes":[
			{"x":0.654,"y":0.1125,"size":40},
			{"x":0.729,"y":0.0775,"size":40},
			{"x":0.709,"y":0.1375,"size":100,"vine":true},
			{"x":0.05,"y":0.1525,"size":100,"enemy":"#ee4035"},
			{"x":0.077,"y":0.38375,"size":60},
			{"x":0.155,"y":0.2875,"size":60},
			{"x":0.128,"y":0.5225,"size":60},
			{"x":0.327,"y":0.615,"size":60},
			{"x":0.485,"y":0.7225,"size":60},
			{"x":0.661,"y":0.73625,"size":100},
			{"x":0.382,"y":0.77,"size":40},
			{"x":0.153,"y":0.665,"size":120}
		],
		"mutateDisabled":true,
		"enemies":["#ee4035"]
	},
	"sample10.jek" : {
		"nodes":[
			{"x":0.079,"y":0.775,"size":100},
			{"x":0.26,"y":0.80625,"size":40},
			{"x":0.339,"y":0.7825,"size":100,"vine":true},
			{"x":0.527,"y":0.8175,"size":40},
			{"x":0.596,"y":0.7825,"size":100},
			{"x":0.357,"y":0.62125,"size":40},
			{"x":0.226,"y":0.57375,"size":100},
			{"x":0.449,"y":0.57,"size":100},
			{"x":0.297,"y":0.345,"size":160,"enemy":"#ee4035"},
			{"x":0.108,"y":0.3075,"size":40},
			{"x":0.226,"y":0.3075,"size":40},
			{"x":0.165,"y":0.43,"size":40},
			{"x":0.513,"y":0.28875,"size":40},
			{"x":0.639,"y":0.2975,"size":40},
			{"x":0.566,"y":0.4225,"size":40},
			{"x":0.149,"y":0.13,"size":100,"enemy":"#ee4035"},
			{"x":0.346,"y":0.11625,"size":100},
			{"x":0.536,"y":0.1275,"size":100,"enemy":"#ee4035"}
		],
		"mutateDisabled":true,
		"enemies":["#ee4035"]
	},
	"sample11.jek" : {
		"nodes":[
			{"x":0.068,"y":0.13375,"size":100,"vine":true},
			{"x":0.192,"y":0.14,"size":60},
			{"x":0.113,"y":0.27125,"size":60},
			{"x":0.316,"y":0.58625,"size":100},
			{"x":0.287,"y":0.5,"size":60},
			{"x":0.415,"y":0.53625,"size":60},
			{"x":0.717,"y":0.27,"size":80},
			{"x":0.662,"y":0.1875,"size":60},
			{"x":0.662,"y":0.37125,"size":60},
			{"x":0.625,"y":0.7675,"size":80},
			{"x":0.752,"y":0.63375,"size":80},
			{"x":0.713,"y":0.77625,"size":140,"enemy":"#ee4035"},
			{"x":0.073,"y":0.73125,"size":60},
			{"x":0.415,"y":0.265,"size":60},
			{"x":0.843,"y":0.1325,"size":60}
		],
		"message" : "An organism with a healthy immune system will gradually become immune to infection. Immunity is specific to a single vine. It causes units to be weaker and eventually the death of the entire vine. Mutate a vine to decrease immunity. Vines cannot grow while mutating. The longer a vine grows the more slowly its immunity rises or falls.",
		"mutateDisabled" : false,
		"enemies":["#ee4035"]
	},
	"sample12.jek" : {"nodes":[{"x":0.42,"y":0.4075,"size":140,"vine":true},{"x":0.182,"y":0.44125,"size":80},{"x":0.693,"y":0.43625,"size":80},{"x":0.3,"y":0.25875,"size":60},{"x":0.593,"y":0.255,"size":60},{"x":0.456,"y":0.27375,"size":40},{"x":0.477,"y":0.70875,"size":40},{"x":0.593,"y":0.68875,"size":80},{"x":0.278,"y":0.69625,"size":80},{"x":0.078,"y":0.20625,"size":40,"enemy":"#ee4035"},{"x":0.861,"y":0.18875,"size":40,"enemy":"#ee4035"},{"x":0.86,"y":0.8325,"size":40,"enemy":"#ee4035"},{"x":0.096,"y":0.84375,"size":40,"enemy":"#ee4035"}],"mutateDisabled":false,"enemies":["#ee4035"]},
	"sample13.jek" : {"nodes":[{"x":0.036,"y":0.11,"size":100,"vine":true},{"x":0.204,"y":0.115,"size":60},{"x":0.164,"y":0.24625,"size":60},{"x":0.024,"y":0.31375,"size":80},{"x":0.125,"y":0.34625,"size":40},{"x":0.248,"y":0.20875,"size":40},{"x":0.724,"y":0.72125,"size":160,"enemy":"#ee4035"},{"x":0.783,"y":0.5225,"size":120,"enemy":"#ee4035"},{"x":0.495,"y":0.76625,"size":140,"enemy":"#ee4035"},{"x":0.296,"y":0.09875,"size":60},{"x":0.218,"y":0.6425,"size":80},{"x":0.368,"y":0.4425,"size":100},{"x":0.519,"y":0.3,"size":60}],"mutateDisabled":false,"enemies":["#ee4035"]},
	"sample14.jek" : {"nodes":[{"x":0.409,"y":0.4075,"size":160},{"x":0.632,"y":0.48,"size":40,"enemy":"#ee4035"},{"x":0.594,"y":0.3275,"size":40},{"x":0.466,"y":0.25125,"size":40,"enemy":"#ee4035"},{"x":0.464,"y":0.66,"size":40,"enemy":"#ee4035"},{"x":0.348,"y":0.63,"size":40},{"x":0.287,"y":0.49375,"size":40,"enemy":"#ee4035"},{"x":0.684,"y":0.6925,"size":100,"vine":true},{"x":0.197,"y":0.17625,"size":120,"vine":true},{"x":0.7,"y":0.10875,"size":120},{"x":0.126,"y":0.745,"size":120}],"mutateDisabled":false,"enemies":["#ee4035"]},
	"sample15.jek" : {"nodes":[{"x":0.125,"y":0.2725,"size":40,"vine":true},{"x":0.239,"y":0.22625,"size":40},{"x":0.371,"y":0.1825,"size":80,"enemy":"#ee4035"},{"x":0.525,"y":0.325,"size":40},{"x":0.558,"y":0.47375,"size":40},{"x":0.45,"y":0.62625,"size":80,"enemy":"#ee4035"},{"x":0.523,"y":0.83375,"size":40},{"x":0.724,"y":0.84625,"size":40},{"x":0.817,"y":0.66375,"size":60,"vine":true},{"x":0.214,"y":0.69125,"size":60},{"x":0.249,"y":0.48375,"size":60},{"x":0.374,"y":0.37875,"size":40},{"x":0.669,"y":0.28125,"size":80,"enemy":"#ee4035"},{"x":0.841,"y":0.22,"size":40},{"x":0.09,"y":0.84,"size":40}],"mutateDisabled":false,"enemies":["#ee4035"]},
	"sample16.jek" : {"nodes":[{"x":0.4,"y":0.40375,"size":140,"vine":true},{"x":0.514,"y":0.31625,"size":80},{"x":0.618,"y":0.24125,"size":60},{"x":0.727,"y":0.2425,"size":40},{"x":0.827,"y":0.24375,"size":40,"enemy":"#ee4035"},{"x":0.474,"y":0.585,"size":100},{"x":0.563,"y":0.7075,"size":80},{"x":0.687,"y":0.71125,"size":60},{"x":0.725,"y":0.61,"size":60},{"x":0.771,"y":0.5325,"size":40},{"x":0.871,"y":0.52625,"size":40},{"x":0.229,"y":0.50625,"size":140},{"x":0.167,"y":0.63625,"size":60},{"x":0.087,"y":0.72375,"size":80},{"x":0.165,"y":0.8225,"size":60},{"x":0.258,"y":0.8125,"size":40,"enemy":"#ee4035"},{"x":0.289,"y":0.2975,"size":80},{"x":0.203,"y":0.21125,"size":80},{"x":0.084,"y":0.225,"size":80},{"x":0.033,"y":0.35,"size":60,"enemy":"#ee4035"},{"x":0.322,"y":0.13875,"size":60},{"x":0.42,"y":0.13125,"size":40,"enemy":"#ee4035"}],"mutateDisabled":false,"enemies":["#ee4035"]},
	"sample17.jek" : {"nodes":[{"x":0.469,"y":0.4625,"size":40},{"x":0.542,"y":0.52875,"size":60},{"x":0.377,"y":0.37375,"size":60},{"x":0.515,"y":0.3225,"size":100},{"x":0.366,"y":0.54125,"size":100},{"x":0.261,"y":0.235,"size":80,"enemy":"#ee4035"},{"x":0.664,"y":0.64375,"size":80,"enemy":"#ee4035"},{"x":0.182,"y":0.7025,"size":140, "vine": true},{"x":0.66,"y":0.13875,"size":140,"enemy":"#ee4035"},{"x":0.192,"y":0.45875,"size":80},{"x":0.738,"y":0.45375,"size":80},{"x":0.432,"y":0.17125,"size":80},{"x":0.452,"y":0.72875,"size":100}],"mutateDisabled":false,"enemies":["#ee4035"]},
	"sample18.jek" : {"nodes":[{"x":0.11,"y":0.185,"size":80},{"x":0.111,"y":0.40625,"size":80},{"x":0.104,"y":0.655,"size":80,"enemy":"#ee4035"},{"x":0.296,"y":0.3,"size":80},{"x":0.29,"y":0.53875,"size":80},{"x":0.277,"y":0.82125,"size":80},{"x":0.441,"y":0.12125,"size":100,"enemy":"#ee4035"},{"x":0.477,"y":0.435,"size":40},{"x":0.476,"y":0.75625,"size":40,"vine":true},{"x":0.619,"y":0.2875,"size":80},{"x":0.625,"y":0.5925,"size":80},{"x":0.606,"y":0.81125,"size":80},{"x":0.835,"y":0.14875,"size":80},{"x":0.822,"y":0.40875,"size":100},{"x":0.815,"y":0.70875,"size":100,"enemy":"#ee4035"}],"mutateDisabled":false,"enemies":["#ee4035"]},
	"sample19.jek" : {"nodes":[{"x":0.459,"y":0.4525,"size":80,"enemy":"#ee4035"},{"x":0.381,"y":0.3575,"size":60},{"x":0.349,"y":0.4775,"size":60},{"x":0.443,"y":0.61875,"size":60},{"x":0.574,"y":0.58875,"size":60},{"x":0.585,"y":0.42625,"size":60},{"x":0.489,"y":0.31375,"size":60},{"x":0.37,"y":0.14875,"size":100},{"x":0.19,"y":0.3375,"size":100},{"x":0.218,"y":0.64,"size":100},{"x":0.522,"y":0.775,"size":100},{"x":0.754,"y":0.51,"size":100},{"x":0.659,"y":0.20375,"size":100},{"x":0.888,"y":0.8925,"size":40,"vine":true}],"mutateDisabled":false,"enemies":["#ee4035"]},
	"sample20.jek" : {"nodes":[{"x":0.482,"y":0.18125,"size":60},{"x":0.458,"y":0.3625,"size":100},{"x":0.427,"y":0.58625,"size":160},{"x":0.128,"y":0.10875,"size":40,"vine":true},{"x":0.322,"y":0.14125,"size":40},{"x":0.656,"y":0.14375,"size":40},{"x":0.842,"y":0.11,"size":40,"vine":true},{"x":0.094,"y":0.8525,"size":100,"enemy":"#ee4035"},{"x":0.278,"y":0.75625,"size":120},{"x":0.621,"y":0.75875,"size":120},{"x":0.821,"y":0.83625,"size":100,"enemy":"#ee4035"},{"x":0.22,"y":0.275,"size":40},{"x":0.76,"y":0.32875,"size":40},{"x":0.124,"y":0.57,"size":100},{"x":0.778,"y":0.5675,"size":100}],"mutateDisabled":false,"enemies":["#ee4035"]},
	"sample21.jek" : {"nodes":[{"x":0.072,"y":0.16875,"size":140,"enemy":"#ee4035"},{"x":0.075,"y":0.40625,"size":80},{"x":0.249,"y":0.235,"size":80},{"x":0.777,"y":0.1375,"size":120,"enemy":"#0392cf"},{"x":0.626,"y":0.215,"size":80},{"x":0.824,"y":0.36375,"size":80},{"x":0.426,"y":0.57375,"size":140,"vine":true},{"x":0.295,"y":0.74,"size":100},{"x":0.579,"y":0.7475,"size":100},{"x":0.445,"y":0.3175,"size":60},{"x":0.644,"y":0.44,"size":60},{"x":0.283,"y":0.44,"size":80}],"mutateDisabled":false,"enemies":["#ee4035","#0392cf"]},
	"sample22.jek" : {"nodes":[{"x":0.115,"y":0.19,"size":140,"enemy":"#ee4035"},{"x":0.097,"y":0.6475,"size":160,"enemy":"#0392cf"},{"x":0.694,"y":0.16375,"size":140},{"x":0.681,"y":0.63625,"size":160,"vine":true},{"x":0.397,"y":0.40375,"size":140},{"x":0.828,"y":0.44625,"size":80},{"x":0.017,"y":0.43,"size":100},{"x":0.428,"y":0.84125,"size":100},{"x":0.413,"y":0.08125,"size":100},{"x":0.332,"y":0.3225,"size":40},{"x":0.318,"y":0.63375,"size":40},{"x":0.606,"y":0.6475,"size":40},{"x":0.618,"y":0.325,"size":40},{"x":0.268,"y":0.4625,"size":40},{"x":0.617,"y":0.47625,"size":40}],"mutateDisabled":false,"enemies":["#ee4035","#0392cf"]},
	"sample23.jek" : {"nodes":[{"x":0.431,"y":0.13625,"size":140,"enemy":"#ee4035"},{"x":0.044,"y":0.38,"size":160,"vine":true},{"x":0.764,"y":0.4175,"size":160,"enemy":"#0392cf"},{"x":0.413,"y":0.70375,"size":160,"enemy":"#f37736"},{"x":0.446,"y":0.42875,"size":100},{"x":0.233,"y":0.2025,"size":100},{"x":0.666,"y":0.2025,"size":80},{"x":0.175,"y":0.68,"size":120},{"x":0.693,"y":0.74875,"size":100},{"x":0.307,"y":0.45625,"size":40},{"x":0.642,"y":0.47,"size":40}],"mutateDisabled":false,"enemies":["#ee4035","#0392cf","#f37736"]},
	"sample24.jek" : {"nodes":[{"x":0.099,"y":0.2025,"size":60},{"x":0.096,"y":0.38125,"size":60},{"x":0.256,"y":0.3125,"size":60},{"x":0.322,"y":0.4875,"size":60},{"x":0.463,"y":0.3975,"size":80},{"x":0.516,"y":0.61,"size":60},{"x":0.727,"y":0.5325,"size":60},{"x":0.751,"y":0.75125,"size":60},{"x":0.055,"y":0.63625,"size":100,"enemy":"#ee4035"},{"x":0.28,"y":0.805,"size":100,"vine":true},{"x":0.405,"y":0.10625,"size":100,"enemy":"#0392cf"},{"x":0.651,"y":0.25625,"size":120,"enemy":"#f37736"},{"x":0.867,"y":0.61375,"size":80}],"mutateDisabled":false,"enemies":["#ee4035","#0392cf","#f37736"]},
	"sample25.jek" : {"nodes":[{"x":0.411,"y":0.3825,"size":160},{"x":0.147,"y":0.175,"size":40,"vine":true},{"x":0.839,"y":0.16375,"size":40,"enemy":"#0392cf"},{"x":0.167,"y":0.845,"size":40,"enemy":"#f37736"},{"x":0.768,"y":0.84625,"size":40,"enemy":"#fdf498"},{"x":0.475,"y":0.1625,"size":40,"enemy":"#ee4035"},{"x":0.432,"y":0.7775,"size":120},{"x":0.123,"y":0.43875,"size":100},{"x":0.773,"y":0.41875,"size":100},{"x":0.278,"y":0.24625,"size":100},{"x":0.652,"y":0.24125,"size":100},{"x":0.261,"y":0.61875,"size":100},{"x":0.644,"y":0.6225,"size":100},{"x":0.855,"y":0.7025,"size":60},{"x":0.082,"y":0.67625,"size":80},{"x":0.477,"y":0.6525,"size":40}],"mutateDisabled":false,"enemies":["#0392cf","#f37736","#fdf498","#ee4035"]},
	"sample26.jek" : {"nodes":[{"x":0.148,"y":0.3525,"size":80},{"x":0.28,"y":0.1975,"size":80},{"x":0.395,"y":0.4525,"size":80},{"x":0.612,"y":0.2875,"size":80},{"x":0.704,"y":0.53375,"size":80},{"x":0.255,"y":0.70625,"size":60,"enemy":"#0392cf"},{"x":0.404,"y":0.7425,"size":80},{"x":0.78,"y":0.36,"size":60,"enemy":"#ee4035"},{"x":0.136,"y":0.1825,"size":60,"vine":true},{"x":0.277,"y":0.825,"size":80},{"x":0.663,"y":0.8025,"size":80,"enemy":"#fdf498"},{"x":0.767,"y":0.7425,"size":40},{"x":0.804,"y":0.845,"size":60,"enemy":"#fdf498"},{"x":0.101,"y":0.545,"size":40},{"x":0.117,"y":0.6125,"size":80},{"x":0.485,"y":0.16625,"size":40,"enemy":"#ee4035"},{"x":0.726,"y":0.13,"size":80,"enemy":"#f37736"}],"mutateDisabled":false,"enemies":["#0392cf","#ee4035","#fdf498","#f37736"]},
	"sample27.jek" : {"nodes":[{"x":0.728,"y":0.0825,"size":160},{"x":0.491,"y":0.11375,"size":120},{"x":0.604,"y":0.315,"size":120},{"x":0.798,"y":0.3675,"size":120},{"x":0.048,"y":0.71875,"size":60,"vine":true},{"x":0.173,"y":0.84,"size":60,"enemy":"#ee4035"},{"x":0.171,"y":0.7075,"size":60,"enemy":"#fdf498"},{"x":0.078,"y":0.5975,"size":60},{"x":0.283,"y":0.8225,"size":60},{"x":0.169,"y":0.55125,"size":80,"enemy":"#0392cf"},{"x":0.283,"y":0.67875,"size":60,"enemy":"#f37736"},{"x":0.806,"y":0.86,"size":60},{"x":0.09,"y":0.15875,"size":60},{"x":0.266,"y":0.35625,"size":60},{"x":0.504,"y":0.605,"size":60},{"x":0.647,"y":0.73,"size":60}],"mutateDisabled":false,"enemies":["#ee4035","#fdf498","#0392cf","#f37736"]},
	"sample28.jek" : {"nodes":[{"x":0.115,"y":0.4225,"size":100,"vine":true},{"x":0.476,"y":0.425,"size":80,"enemy":"#0392cf"},{"x":0.79,"y":0.4175,"size":100,"enemy":"#fdf498"},{"x":0.272,"y":0.4125,"size":100,"enemy":"#ee4035"},{"x":0.638,"y":0.42,"size":100,"enemy":"#f37736"},{"x":0.394,"y":0.6175,"size":80},{"x":0.372,"y":0.25,"size":100},{"x":0.574,"y":0.305,"size":60},{"x":0.564,"y":0.6025,"size":80},{"x":0.186,"y":0.2275,"size":100},{"x":0.202,"y":0.65,"size":80},{"x":0.733,"y":0.255,"size":60},{"x":0.726,"y":0.65875,"size":80},{"x":0.023,"y":0.25,"size":100},{"x":0.019,"y":0.57375,"size":100},{"x":0.35,"y":0.8725,"size":40},{"x":0.654,"y":0.1675,"size":40},{"x":0.301,"y":0.11125,"size":40},{"x":0.644,"y":0.77875,"size":40},{"x":0.238,"y":0.895,"size":40,"enemy":"#0392cf"},{"x":0.195,"y":0.0925,"size":40,"enemy":"#0392cf"},{"x":0.876,"y":0.62625,"size":60},{"x":0.882,"y":0.29875,"size":60}],"mutateDisabled":false,"enemies":["#0392cf","#fdf498","#ee4035","#f37736"]},
	"sample29.jek" : {"nodes":[{"x":0.77,"y":0.7725,"size":100,"vine":true},{"x":0.235,"y":0.745,"size":80,"enemy":"#ee4035"},{"x":0.459,"y":0.445,"size":80,"enemy":"#0392cf"},{"x":0.657,"y":0.19125,"size":80,"enemy":"#ee4035"},{"x":0.109,"y":0.42375,"size":80,"enemy":"#fdf498"},{"x":0.341,"y":0.16125,"size":80,"enemy":"#f37736"},{"x":0.483,"y":0.25,"size":80},{"x":0.268,"y":0.505,"size":80},{"x":0.147,"y":0.185,"size":100},{"x":0.076,"y":0.6875,"size":80},{"x":0.327,"y":0.3425,"size":60},{"x":0.385,"y":0.8125,"size":100},{"x":0.692,"y":0.355,"size":100},{"x":0.505,"y":0.64125,"size":100},{"x":0.507,"y":0.08,"size":60},{"x":0.037,"y":0.29875,"size":60},{"x":0.607,"y":0.50625,"size":60}],"mutateDisabled":false,"enemies":["#ee4035","#0392cf","#fdf498","#f37736"]},
	"sample30.jek" : {"nodes":[{"x":0.427,"y":0.76,"size":120,"vine":true},{"x":0.211,"y":0.72375,"size":80},{"x":0.449,"y":0.5175,"size":80},{"x":0.665,"y":0.71125,"size":80},{"x":0.192,"y":0.4,"size":100},{"x":0.643,"y":0.4125,"size":100},{"x":0.059,"y":0.57875,"size":80,"enemy":"#ee4035"},{"x":0.829,"y":0.56,"size":80,"enemy":"#ee4035"},{"x":0.416,"y":0.22875,"size":120,"enemy":"#ee4035"},{"x":0.073,"y":0.3125,"size":60,"enemy":"#0392cf"},{"x":0.272,"y":0.1825,"size":60,"enemy":"#f37736"},{"x":0.677,"y":0.18625,"size":60,"enemy":"#fdf498"},{"x":0.861,"y":0.37375,"size":60,"enemy":"#0392cf"},{"x":0.439,"y":0.06125,"size":60},{"x":0.33,"y":0.615,"size":60},{"x":0.592,"y":0.61,"size":60}],"mutateDisabled":false,"enemies":["#ee4035","#0392cf","#f37736","#fdf498"]},
};  
